import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtempSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {execFileSync} from 'node:child_process';
process.env.DATA_DIR=mkdtempSync(join(tmpdir(),'retirement-'));
execFileSync(process.execPath,['scripts/migrate.mjs']);
const {connection:db}=await import('../server/database.mjs');
const {retireAsset}=await import('../server/asset-retirement.mjs');
const actor={id:'it',name:'IT Admin',role:'admin'};
const body={assetId:'asset',retirement_date:'2026-09-25',retirement_reason:'Beyond repair'};
const now='2026-09-25T01:00:00Z';
function reset(){db.exec('DELETE FROM asset_events; DELETE FROM maintenance; DELETE FROM assets;');db.prepare("INSERT INTO assets(id,tag,name,kind,serial,seats,state,details) VALUES('asset','TEST-LT','Test laptop','Hardware','',1,'Maintenance',?)").run(JSON.stringify({category:'Laptop',purchase_date:'2026-01-01'}));db.exec("INSERT INTO maintenance(id,asset_id,type,issue,opened_date,created_at) VALUES('service','asset','Inspection','Needs evaluation','2026-09-24','2026-09-24')");}
test('retirement closes maintenance without losing records and is not repeatable',()=>{reset();retireAsset(body,actor,now);assert.equal(db.prepare('SELECT state FROM assets').get().state,'Retired');const m=db.prepare('SELECT * FROM maintenance').get();assert.equal(m.closure_outcome,'Retired');assert.equal(m.completed_date,body.retirement_date);assert.equal(m.issue,'Needs evaluation');assert.match(m.work_done,/Beyond repair/);assert.equal(db.prepare('SELECT COUNT(*) n FROM asset_events').get().n,1);assert.throws(()=>retireAsset(body,actor,now),/already retired/);assert.equal(db.prepare('SELECT COUNT(*) n FROM asset_events').get().n,1);});
test('invalid dates and missing reasons do not mutate inventory',()=>{reset();for(const patch of [{retirement_date:'2026-02-30'},{retirement_date:'2026-09-26'},{retirement_date:'2026-09-23'},{retirement_reason:' '}])assert.throws(()=>retireAsset({...body,...patch},actor,now));assert.equal(db.prepare('SELECT state FROM assets').get().state,'Maintenance');assert.equal(db.prepare('SELECT completed_date FROM maintenance').get().completed_date,null);});
test('ordinary users and unresolved source custody are blocked',()=>{reset();assert.throws(()=>retireAsset(body,{role:'user'},now),/administrators/);db.prepare('UPDATE assets SET details=?').run(JSON.stringify({custodian:'Unconfirmed employee'}));assert.throws(()=>retireAsset(body,actor,now),/custody/);assert.equal(db.prepare('SELECT state FROM assets').get().state,'Maintenance');});
test('active assignment is blocked and returned assignment history is retained',()=>{reset();db.exec("INSERT INTO employees(id,code,name,email,department,role,start_date,status) VALUES('emp','TEST','Employee','e@test.local','IT','Test','2026-01-01','Active');INSERT INTO assignments(id,employee_id,asset_id,assigned_at) VALUES('assignment','emp','asset','2026-09-24')");assert.throws(()=>retireAsset(body,actor,now),/custody/);db.exec("UPDATE assignments SET resolved_at='2026-09-25',resolution='Returned'");retireAsset(body,actor,now);assert.equal(db.prepare('SELECT COUNT(*) n FROM assignments').get().n,1);assert.deepEqual(db.prepare('PRAGMA foreign_key_check').all(),[]);});
test('reserved and borrowed hardware cannot retire; cancelled reservation can',()=>{db.exec("INSERT INTO assets(id,tag,name,kind,serial,seats,state,details) VALUES('loan-asset','LOAN','Loan laptop','Hardware','',1,'Ready','{}');INSERT INTO borrowings(id,employee_id,purpose,starts_at,due_at,status,created_at,created_by,employee_snapshot) VALUES('loan','emp','Test','2026-09-24','2026-09-26','Reserved','2026-09-24','it','{}');INSERT INTO borrowing_items(id,borrowing_id,asset_id,asset_snapshot,condition_out) VALUES('item','loan','loan-asset','{}','Good')");const request={...body,assetId:'loan-asset'};assert.throws(()=>retireAsset(request,actor,now),/borrowing/);db.exec("UPDATE borrowings SET status='Borrowed'");assert.throws(()=>retireAsset(request,actor,now),/borrowing/);db.exec("UPDATE borrowings SET status='Cancelled'");retireAsset(request,actor,now);assert.equal(db.prepare("SELECT state FROM assets WHERE id='loan-asset'").get().state,'Retired');});
