import test from 'node:test';import assert from 'node:assert/strict';import {mkdtempSync} from 'node:fs';import {tmpdir} from 'node:os';import {join} from 'node:path';import {execFileSync} from 'node:child_process';
process.env.DATA_DIR=mkdtempSync(join(tmpdir(),'cancel-lifecycle-'));execFileSync(process.execPath,['scripts/migrate.mjs']);
const {connection:db}=await import('../server/database.mjs');const {cancelLifecycle}=await import('../server/lifecycle-cancellation.mjs');
const actor={id:'it',name:'IT',role:'admin'};
function seed(id,status){db.prepare('INSERT INTO employees(id,code,name,email,department,role,start_date,status,end_date,departure_reason) VALUES(?,?,?,?,?,?,?,?,?,?)').run(id,id,id,id+'@example.test','IT','Staff','2026-01-01',status,'2026-09-30','Resignation')}
seed('leaver','Offboarding');seed('new','Onboarding');
test('requires permission, reason and confirmation without changing state',()=>{const b={employeeId:'leaver',kind:'Offboarding',reason:'Mistake',confirmed:true};assert.throws(()=>cancelLifecycle(b,{role:'user'}));assert.throws(()=>cancelLifecycle({...b,reason:''},actor));assert.throws(()=>cancelLifecycle({...b,confirmed:false},actor));assert.equal(db.prepare("SELECT status FROM employees WHERE id='leaver'").get().status,'Offboarding')});
test('cancellation restores status and preserves audit; stale retry rejected',()=>{const b={employeeId:'leaver',kind:'Offboarding',reason:'Started by mistake',confirmed:true};cancelLifecycle(b,actor);const e=db.prepare("SELECT * FROM employees WHERE id='leaver'").get();assert.equal(e.status,'Active');assert.equal(e.end_date,null);assert.equal(e.departure_reason,'');assert.equal(db.prepare('SELECT count(*) n FROM events').get().n,1);assert.throws(()=>cancelLifecycle(b,actor))});
test('mistaken onboarding may be cancelled without deleting employee',()=>{cancelLifecycle({employeeId:'new',kind:'Onboarding',reason:'Existing employee',confirmed:true},actor);assert.equal(db.prepare("SELECT status FROM employees WHERE id='new'").get().status,'Active');assert.equal(db.prepare('SELECT count(*) n FROM security_events').get().n,2)});
