import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtempSync,readFileSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {execFileSync} from 'node:child_process';
process.env.DATA_DIR=mkdtempSync(join(tmpdir(),'anchored-test-'));
process.env.APP_ORIGIN='http://localhost:3000';process.env.NODE_ENV='test';
execFileSync(process.execPath,['scripts/migrate.mjs'],{env:process.env});
const {connection,adapter}=await import('../server/database.mjs');
const auth=await import('../server/auth.mjs');
const password='A long test-only password!';const encoded=await auth.passwordHash(password);
for(const [id,role] of [['s','super_admin'],['a','admin'],['u','user']])connection.prepare('INSERT INTO app_users(id,username,name,role,password_hash,must_change_password,created_at) VALUES(?,?,?,?,?,0,?)').run(id,id+'test',role,role,encoded,new Date().toISOString());
const request=token=>new Request('http://localhost:3000/api/workspace',{headers:{cookie:'anchored_session='+token}});
test('password hashing and validation',async()=>{assert(!encoded.includes(password));assert(await auth.verifyPassword(password,encoded));assert(!await auth.verifyPassword('wrong',encoded));assert.throws(()=>auth.passwordRules('short'));});
test('unauthenticated and lesser roles are denied',()=>{assert.throws(()=>auth.currentUser(request('')),e=>e.status===401);const token=auth.startSession('u');assert.throws(()=>auth.requireRole(request(token),['super_admin','admin']),e=>e.status===403);assert.equal(auth.currentUser(request(token)).id,'u');});
test('role changes and disabled accounts take effect in existing sessions',()=>{const t=auth.startSession('a');assert.equal(auth.requireRole(request(t),['admin']).id,'a');connection.prepare("UPDATE app_users SET role='user' WHERE id='a'").run();assert.throws(()=>auth.requireRole(request(t),['admin']),e=>e.status===403);connection.prepare("UPDATE app_users SET active=0 WHERE id='a'").run();assert.throws(()=>auth.currentUser(request(t)),e=>e.status===401)});
test('logout revokes server-side session',()=>{const t=auth.startSession('s');auth.logout(request(t));assert.throws(()=>auth.currentUser(request(t)),e=>e.status===401)});
test('origin checks reject cross-site mutations',()=>{assert.throws(()=>auth.checkOrigin(new Request('http://localhost:3000/api/auth',{headers:{origin:'https://attacker.example'}})),e=>e.status===403);auth.checkOrigin(new Request('http://localhost:3000/api/auth',{headers:{origin:'http://localhost:3000'}}))});
test('temporary password blocks business access',()=>{connection.prepare("UPDATE app_users SET must_change_password=1 WHERE id='u'").run();const t=auth.startSession('u');assert.throws(()=>auth.currentUser(request(t)),e=>e.status===403);assert.equal(auth.currentUser(request(t),true).id,'u')});
test('SQLite adapter rolls back partial batches',async()=>{await assert.rejects(adapter.batch([adapter.prepare("INSERT INTO assets(id,tag,name,kind) VALUES('rollback','rollback','Test','Hardware')"),adapter.prepare("INSERT INTO assets(id,tag,name,kind) VALUES('rollback','duplicate','Test','Hardware')")]));assert.equal(connection.prepare("SELECT id FROM assets WHERE id='rollback'").get(),undefined)});
test('rate limit bounds password attempts',()=>{for(let i=0;i<10;i++)auth.throttle('bounded-user');assert.throws(()=>auth.throttle('bounded-user'),e=>e.status===429)});
test.after(()=>connection.close());
