'use client';
import {ThemeToggle} from './theme-toggle';
import {Menu} from 'lucide-react';
import {DropdownMenu,DropdownMenuTrigger,DropdownMenuContent,DropdownMenuItem,DropdownMenuGroup,DropdownMenuLabel,DropdownMenuSeparator} from './ui/dropdown-menu';
import {Borrowing} from './borrowing';
import {BrandLogo} from './brand-logo';
import {ManageAccess} from './manage-access';
import {DepartureRecords} from './departure-records';
import {useEffect,useState,type FormEvent,type ReactNode} from 'react';
type User={id:string;username:string;email:string;name:string;role:string;employee_id:string|null;must_change_password:boolean};
async function api(path:string,body?:unknown){const r=await fetch(path,{method:body?'POST':'GET',headers:body?{'Content-Type':'application/json'}:undefined,body:body?JSON.stringify(body):undefined});const data:any=await r.json();if(!r.ok)throw Error(data.error||'Request failed');return data;}
export function AccessShell({children}:{children:ReactNode}){
const [user,setUser]=useState<User|null>(null),[ready,setReady]=useState(false),[error,setError]=useState(''),[busy,setBusy]=useState(false),[section,setSection]=useState('operations'),[change,setChange]=useState(false);
useEffect(()=>{api('/api/auth').then(x=>setUser(x.user)).catch(()=>{}).finally(()=>setReady(true))},[]);
async function signIn(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError('');const b=Object.fromEntries(new FormData(e.currentTarget));try{setUser((await api('/api/auth',{...b,action:'login'})).user)}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
async function signOut(){try{await api('/api/auth',{action:'logout'});setUser(null);setSection('operations');setChange(false)}catch(e){setError((e as Error).message)}}
async function password(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError('');const b=Object.fromEntries(new FormData(e.currentTarget));if(b.password!==b.confirm){setBusy(false);setError('New passwords do not match.');return}try{await api('/api/auth',{...b,action:'changePassword'});setUser(null);setChange(false);setError('Password changed. Sign in with your new password.')}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
if(!ready)return <main className="access-card">Loading AnchorEd Asset Management…</main>;
if(!user)return <main className="access-screen"><div className="login-theme"><ThemeToggle/></div><form className="access-card" onSubmit={signIn}><div className="login-brand"><BrandLogo variant="login"/><h1>Asset Management</h1></div><p>Sign in to your company workspace.</p><label>Username<input name="username" autoComplete="username" required maxLength={64}/></label><label>Password<input name="password" type="password" autoComplete="current-password" maxLength={128} required/></label>{error&&<p role="alert">{error}</p>}<button className="primary" disabled={busy}>{busy?'Signing in…':'Sign in'}</button><small>Need access or a password reset? Contact your Super Admin.</small></form></main>;
if(user.must_change_password||change)return <main className="access-screen"><div className="login-theme"><ThemeToggle/></div><form className="access-card" onSubmit={password}><BrandLogo variant="login"/><h1>Change password</h1><p>Use 12–128 characters. All existing sessions will be signed out.</p><label>Current password<input name="currentPassword" type="password" autoComplete="current-password" required/></label><label>New password<input name="password" type="password" autoComplete="new-password" minLength={12} maxLength={128} required/></label><label>Confirm new password<input name="confirm" type="password" autoComplete="new-password" minLength={12} maxLength={128} required/></label>{error&&<p role="alert">{error}</p>}<button className="primary" disabled={busy}>Change password</button><button type="button" className="secondary" onClick={signOut}>Sign out</button></form></main>;
return <><header className={"access-bar" + (section==='operations' && user.role!=='user' ? " workspace-account-bar" : "")}><BrandLogo variant="header"/><strong>Asset Management</strong><div className="account-navigation"><ThemeToggle/><DropdownMenu><DropdownMenuTrigger className="account-menu-trigger" aria-label="Account menu"><Menu size={23}/></DropdownMenuTrigger><DropdownMenuContent align="end" className="account-menu-content"><DropdownMenuGroup><DropdownMenuLabel>{user.name}<small>{user.role.replace('_',' ')}</small></DropdownMenuLabel>{['super_admin','admin'].includes(user.role)&&<DropdownMenuItem onClick={()=>setSection(section==='users'?'operations':'users')}>{section==='users'?'IT workspace':'Manage access'}</DropdownMenuItem>}<DropdownMenuItem onClick={()=>{setError('');setChange(true)}}>Change password</DropdownMenuItem><DropdownMenuSeparator/><DropdownMenuItem onClick={signOut}>Sign out</DropdownMenuItem></DropdownMenuGroup></DropdownMenuContent></DropdownMenu></div></header>{error&&<p role="alert">{error}</p>}{section==='users'&&['super_admin','admin'].includes(user.role)?<ManageAccess role={user.role}/>:user.role==='user'?<EmployeePortal/>:children}</>;
}
function EmployeePortal(){
const [data,setData]=useState<any>(null),[error,setError]=useState('');useEffect(()=>{api('/api/me').then(setData).catch(e=>setError(e.message))},[]);
if(error)return <main className="access-management"><p role="alert">{error}</p></main>;if(!data)return <main className="access-management">Loading your records…</main>;
return <main className="access-management"><h1>My equipment and access</h1><p>{data.employee?`${data.employee.name} · ${data.employee.code} · ${data.employee.department}`:'Your login is not linked to an employee. Contact your Super Admin.'}</p><h2>Equipment and software</h2><div className="access-table"><table><thead><tr><th>Item</th><th>Tag / serial</th><th>Issued</th><th>Status</th></tr></thead><tbody>{data.assignments.map((a:any)=><tr key={a.id}><td>{a.name}</td><td>{a.tag}<small>{a.serial}</small></td><td>{a.assigned_at.slice(0,10)}</td><td>{a.resolved_at?`${a.resolution} · ${a.resolved_at.slice(0,10)}`:'Assigned to you'}</td></tr>)}</tbody></table></div><h2>Accounts</h2>{data.accounts.map((a:any)=><p key={a.id}>{a.provider} · {a.username} · {a.status}</p>)}{!data.accounts.length&&<p>No account records have been linked yet.</p>}<h2>Other provisioned items</h2>{data.tasks.map((t:any)=><p key={t.id}>{t.label} · Quantity {t.quantity} · {t.state}</p>)}{data.employee&&['Offboarding','Offboarded'].includes(data.employee.status)&&<DepartureRecords employeeId={data.employee.id}/>}{data.employee&&<Borrowing employeeId={data.employee.id}/>}<h2>My documents</h2>{data.forms.map((f:any)=><details key={f.id}><summary>{f.type} · {f.status} · {f.submitted_at.slice(0,10)}</summary><DocumentDetails payload={JSON.parse(f.payload)}/>{data.files.filter((x:any)=>x.form_id===f.id).map((x:any)=><p key={x.id}><a href={'/api/form-files?id='+encodeURIComponent(x.id)} target="_blank" rel="noreferrer">{x.name}</a></p>)}</details>)}{!data.forms.length&&<p>No documents recorded yet.</p>}</main>
}
function DocumentDetails({payload:p}:{payload:any}){return <div className="document-details"><p>Date: {p.date||"Not recorded"}</p><p>Employee: {p.employee?.name}</p>{p.reason&&<p>Reason: {p.reason}</p>}{p.notes&&<p>Notes: {p.notes}</p>}{p.items?.map((i:any,index:number)=><p key={index}>{i.name} · {i.tag} · {i.condition}</p>)}{p.signature&&<p>Acknowledged by: {p.signature}</p>}</div>}
