'use client';
import {useEffect,useState,type FormEvent} from 'react';
type Upload={id:string;name:string;signed_date:string;notes:string;uploaded_by_name:string};
export function AcknowledgementUploads({employeeId}:{employeeId:string}){
 const [rows,setRows]=useState<Upload[]>([]),[error,setError]=useState(''),[busy,setBusy]=useState(false),[loaded,setLoaded]=useState(false);
 async function load(){const r=await fetch('/api/acknowledgement-uploads?employeeId='+encodeURIComponent(employeeId));const d=await r.json() as {rows:Upload[];error?:string};if(!r.ok)throw Error(d.error||'Could not load documents');setRows(d.rows);setLoaded(true)}
 useEffect(()=>{load().catch(e=>setError(e.message))},[employeeId]);
 async function upload(e:FormEvent<HTMLFormElement>){e.preventDefault();const form=e.currentTarget,b=new FormData(form);b.set('employeeId',employeeId);setBusy(true);setError('');try{const r=await fetch('/api/acknowledgement-uploads',{method:'POST',body:b});const d=await r.json() as {error?:string};if(!r.ok)throw Error(d.error||'Upload failed');await load();form.reset()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 return <section className="employee-kit"><h3>Signed acknowledgement uploads</h3><p>Attach the employee’s existing signed form. Uploading preserves the document without creating or changing asset assignments.</p>{error&&<p role="alert" className="error">{error}</p>}{loaded&&!rows.length&&<p>No signed file uploaded yet. This does not mean the employee has not signed a paper form.</p>}{rows.map(r=><div className="record-section" key={r.id}><a className="row-link" href={'/api/acknowledgement-uploads?id='+r.id}>Download {r.name}</a><p>Signed {r.signed_date} · Uploaded by {r.uploaded_by_name}</p><p>{r.notes}</p></div>)}<details><summary>Upload existing signed form</summary><form onSubmit={upload}><label className="field">Signed form (PDF, JPG or PNG, up to 8 MB)<input name="file" type="file" accept="application/pdf,image/jpeg,image/png" required/></label><label className="field">Date signed<input name="signed_date" type="date" required/></label><label className="field">Covered asset control numbers / notes<textarea name="notes" maxLength={2000} placeholder="For example: LT210, charger and laptop bag"/></label><button className="primary" disabled={busy}>{busy?'Uploading…':'Upload signed form'}</button></form></details></section>
}
