'use client';
import {useEffect,useState,type FormEvent} from 'react';
type Row={id:string;status:string;expected:string;observed:string;discrepancies:string;checked_at:string;checked_by_name:string;resolution:string;resolved_at:string;resolved_by:string};
export function AssetVerification({assetId}:{assetId:string}){
 const [rows,setRows]=useState<Row[]>([]),[expected,setExpected]=useState<Record<string,string>>({}),[error,setError]=useState(''),[busy,setBusy]=useState(false),[loaded,setLoaded]=useState(false);
 async function load(){const r=await fetch('/api/asset-verifications?assetId='+encodeURIComponent(assetId));const d=await r.json() as {error?:string;rows:Row[];expected:Record<string,string>};if(!r.ok)throw Error(d.error||'Unable to load verifications');setRows(d.rows);setExpected(d.expected);setLoaded(true)}
 useEffect(()=>{load().catch(e=>setError(e.message))},[assetId]);
 async function save(e:FormEvent<HTMLFormElement>,extra:Record<string,string>){e.preventDefault();const form=e.currentTarget;setBusy(true);setError('');try{const r=await fetch('/api/asset-verifications',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...Object.fromEntries(new FormData(form)),...extra,assetId})});const d=await r.json() as {error?:string;rows:Row[];expected:Record<string,string>};if(!r.ok)throw Error(d.error||'Unable to save');await load();form.reset()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 return <section className="record-section"><h3>Physical verification & QR label</h3><a className="button" href={'/api/asset-label?assetId='+encodeURIComponent(assetId)} target="_blank" rel="noreferrer">Open printable QR label</a><p>Compare the actual equipment with the recorded details. Differences remain open until IT documents a resolution.</p>{error&&<p role="alert" className="error">{error}</p>}{loaded&&<details><summary>Record inspection</summary><form onSubmit={e=>save(e,{action:'inspect'})}><p>Recorded custodian: {expected.custodian||'None recorded'} Â· Location: {expected.location||'Not recorded'}</p><p>Recorded serial: {expected.serial||'Not recorded'} Â· Condition: {expected.condition||'Not recorded'}</p>{['serial','custodian','location'].map(k=><label className="field" key={k}>Observed {k}<input name={k} maxLength={2000} required={k==='location'} placeholder={k==='custodian'?'Employee name, shared custody, or blank if unassigned':undefined}/></label>)}<label className="field">Observed condition<select name="condition" required><option value="">Choose condition</option>{['New','Good','Fair','Damaged','Not found'].map(x=><option key={x}>{x}</option>)}</select></label><label className="field">Inspection notes<textarea name="notes" maxLength={2000}/></label><button disabled={busy}>Save inspection</button></form></details>}{!rows.length&&loaded&&<p>No inspections recorded yet.</p>}{rows.map(r=><details key={r.id}><summary>{r.status} Â· {new Date(r.checked_at).toLocaleString()} Â· {r.checked_by_name}</summary><p>Differences: {JSON.parse(r.discrepancies).join(', ')||'None'}</p><div style={{overflowX:'auto'}}><table><thead><tr><th>Field</th><th>Recorded at inspection</th><th>Observed</th></tr></thead><tbody>{['serial','custodian','location','condition'].map(k=><tr key={k}><td>{k}</td><td>{JSON.parse(r.expected)[k]||'Not recorded'}</td><td>{JSON.parse(r.observed)[k]||'Not recorded'}</td></tr>)}</tbody></table></div><p>{JSON.parse(r.observed).notes}</p>{r.status==='Open'?<form onSubmit={e=>save(e,{action:'resolve',id:r.id})}><label className="field">Resolution and supporting reference<textarea name="resolution" required maxLength={4000}/></label><p>Update the asset or assignment separately if required. Resolving this finding does not change custody.</p><button disabled={busy}>Record resolution</button></form>:r.resolution&&<p>{r.resolution} Â· {r.resolved_by} Â· {r.resolved_at}</p>}</details>)}</section>
}
