'use client';
import {useState} from 'react';
import {reportCsv} from '@/lib/audit-export';
type Report={report_id:string;report:string;generated_at:string;generated_by:string;sha256:string;scope:string;row_count:number;rows:Record<string,unknown>[]};
const reports=[['verifications','Physical asset verification'],['inventory','Asset inventory'],['provisioning','Employee asset assignments'],['accounts','Accounts & system access'],['accessories','Kit items & accessories'],['offboarding','Offboarding & clearance'],['review','Imported history exceptions'],['activity','Administrative activity']];
export function AuditReports(){
 const [type,setType]=useState('inventory'),[report,setReport]=useState<Report|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[page,setPage]=useState(1);
 async function generate(){setBusy(true);setError('');setReport(null);try{const r=await fetch('/api/audit-reports?type='+type);const data=await r.json() as Report&{error?:string};if(!r.ok)throw Error(data.error||'Unable to generate report');setReport(data);setPage(1)}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 function download(format:'csv'|'json'){if(!report)return;const blob=new Blob([format==='csv'?reportCsv(report):JSON.stringify(report,null,2)],{type:format==='csv'?'text/csv;charset=utf-8':'application/json'});const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`anchored-${report.report}-${report.report_id}.${format}`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
 const pages=Math.max(1,Math.ceil((report?.rows.length||0)/10)),keys=Object.keys(report?.rows[0]||{});
 return <section className="panel p-5"><h2 className="font-semibold text-lg">Audit reporting</h2><p className="text-sm my-3">Generate a dated snapshot of records and outstanding obligations. Exports include a report ID, generator and verification hash. Imported history and recorded sign-offs still require supporting evidence.</p>
 <div className="flex flex-wrap items-end gap-3 my-4"><label className="field">Report<select value={type} disabled={busy} onChange={e=>{setType(e.target.value);setReport(null)}}>{reports.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><button className="primary" disabled={busy} onClick={generate}>{busy?'Generating…':'Generate report'}</button></div>
 {error&&<p role="alert" className="error">{error}</p>}{report&&<><div className="text-sm my-4"><strong>{report.row_count} records</strong> · Generated {new Date(report.generated_at).toLocaleString()}<p>Report ID: {report.report_id}</p><p>{report.scope}</p></div><div className="flex gap-3 flex-wrap mb-4"><button className="secondary" onClick={()=>download('csv')}>Download CSV</button><button className="secondary" onClick={()=>download('json')}>Download verification JSON</button></div><div className="overflow-x-auto"><table className="text-sm w-full"><thead><tr>{keys.map(k=><th className="p-2 text-left whitespace-nowrap" key={k}>{k.replaceAll('_',' ')}</th>)}</tr></thead><tbody>{report.rows.slice((page-1)*10,page*10).map((r,i)=><tr key={i}>{keys.map(k=><td className="p-2 border-t min-w-28 max-w-sm break-words" key={k}>{r[k]===null||r[k]===''?'—':String(r[k])}</td>)}</tr>)}</tbody></table></div>{!report.rows.length&&<p>No records in this report.</p>}<div className="flex items-center gap-3 mt-4"><button className="secondary" disabled={page===1} onClick={()=>setPage(page-1)}>Previous</button><span>Page {page} of {pages}</span><button className="secondary" disabled={page===pages} onClick={()=>setPage(page+1)}>Next</button></div></>}
 </section>
}
