'use client';
import {useState} from 'react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from './ui/dialog';
export function CancelLifecycle({employee,refresh}:{employee:{id:string;name:string;status:string};refresh:()=>Promise<void>}){
 const [open,setOpen]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('');
 if(!['Onboarding','Offboarding'].includes(employee.status))return null;
 return <><button className="secondary" onClick={()=>{setError('');setOpen(true)}}>Cancel {employee.status.toLowerCase()}</button><Dialog open={open} onOpenChange={v=>{if(!busy)setOpen(v)}}><DialogContent><DialogTitle>Cancel {employee.status.toLowerCase()}</DialogTitle><DialogDescription>{employee.name}. Use this to correct a workflow started by mistake. Asset returns, account deactivations, forms and history remain unchanged.</DialogDescription><form onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);setBusy(true);setError('');try{const r=await fetch('/api/workspace',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'cancelLifecycle',employeeId:employee.id,kind:employee.status,restoreStatus:f.get('restoreStatus')||'Active',reason:f.get('reason'),confirmed:f.get('confirmed')==='on'})});const d=await r.json() as {error?:string};if(!r.ok)throw Error(d.error);await refresh();setOpen(false)}catch(e){setError((e as Error).message)}finally{setBusy(false)}}}>
 {employee.status==='Offboarding'?<label className="field">Restore employee to<select name="restoreStatus"><option>Active</option><option>Onboarding</option></select></label>:<p>The employee will become Active. For a withdrawn new hire with outstanding items, use offboarding to recover equipment and revoke access.</p>}
 <label className="field">Cancellation reason<textarea name="reason" required maxLength={1000}/></label><label><input name="confirmed" type="checkbox" required/> I understand completed actions will not be reversed.</label>{error&&<p role="alert" className="error">{error}</p>}<div className="form-actions"><button type="button" className="secondary" disabled={busy} onClick={()=>setOpen(false)}>Keep workflow</button><button className="primary" disabled={busy}>{busy?'Saving…':'Confirm cancellation'}</button></div></form></DialogContent></Dialog></>;
}
