'use client';
import {ManagerHandovers} from './manager-handovers';
import {useEffect,useState} from 'react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from './ui/dialog';
type Document={id:string;type:string;signer_name:string;signed_at:string;note:string};
type Departure={id:string;name:string;code:string;department:string;status:string;end_date:string;departure_reason:string;documents:Document[];turnoverBlockers:string[];clearanceBlockers:string[]};
type Data={employees:Departure[];signer:{name:string;username:string};canSign:boolean};
export function DepartureRecords({employeeId,onEmployee,refresh,version=''}:{employeeId?:string;onEmployee?:(id:string)=>void;refresh?:()=>Promise<void>;version?:string}){
 const [data,setData]=useState<Data>({employees:[],signer:{name:'',username:''},canSign:false}),[error,setError]=useState(''),[search,setSearch]=useState(''),[filter,setFilter]=useState('All departures'),[page,setPage]=useState(1),[sign,setSign]=useState<{employee:Departure;type:string}|null>(null),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 async function load(){const r=await fetch('/api/departures'+(employeeId?'?employeeId='+encodeURIComponent(employeeId):''));const d=await r.json() as Data & {error?:string};if(!r.ok)throw Error(d.error);setData(d)}
 useEffect(()=>{void load().catch(e=>setError(e.message))},[employeeId,version]);
 const rows=data.employees.filter(e=>(filter==='All departures'||filter==='Resigned'?filter==='All departures'||e.departure_reason==='Resignation':e.status===filter)&&`${e.name} ${e.code} ${e.department}`.toLowerCase().includes(search.toLowerCase())),pages=Math.max(1,Math.ceil(rows.length/8)),current=Math.min(page,pages);
 async function signForm(form:HTMLFormElement){if(!sign)return;setBusy(true);setError('');const fields=Object.fromEntries(new FormData(form));const payload={...fields,action:'sign',employeeId:sign.employee.id,type:sign.type,confirmed:fields.confirmed==='on'};try{const r=await fetch('/api/departures',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const d=await r.json() as {error?:string};if(!r.ok)throw Error(d.error);setSign(null);await load();await refresh?.();setMessage('IT sign-off saved. The signed form is ready to view or print.')}catch(e){setError((e as Error).message)}finally{form.reset();setBusy(false)}}
 return <section className="departure-records"><h2>{employeeId?'IT clearance and turnover':'Resigned employees & clearance'}</h2><p>Keep each departure linked to its signed IT documents. Turnover confirms equipment receipt; clearance confirms all recorded equipment and access obligations are resolved.</p>{error&&!sign&&<p className="error" role="alert">{error}</p>}{message&&<p className="success" role="status">{message}</p>}{!employeeId&&<div className="toolbar"><label className="field">Search departed employees<input value={search} onChange={e=>{setSearch(e.target.value);setPage(1)}}/></label><label className="field">Show<select value={filter} onChange={e=>{setFilter(e.target.value);setPage(1)}}>{['All departures','Resigned','Offboarding','Offboarded'].map(v=><option key={v}>{v}</option>)}</select></label></div>}
 {rows.slice((current-1)*8,current*8).map(e=><article className="panel mb-4" key={e.id}><div className="section-head"><div><h3>{e.name}</h3><small>{e.code} · {e.department}</small></div><span className={'badge '+e.status}>{e.status==='Offboarded'?'Offboarded':e.status}</span></div><p>Last working day: {e.end_date||'Not recorded'} · Reason: {e.departure_reason||'Not recorded'}</p>{onEmployee&&<button className="secondary" onClick={()=>onEmployee(e.id)}>Open employee profile</button>}{data.canSign&&<ManagerHandovers employeeId={e.id} onChange={async()=>{await load();await refresh?.()}}/>}<div className="departure-documents">{['Turnover','Clearance'].map(type=>{const doc=e.documents.find(d=>d.type===type),pending=type==='Turnover'?e.turnoverBlockers:e.clearanceBlockers;return <section key={type}><h3>{type} form</h3>{doc?<><span className="badge Active">Signed by IT</span><p>{doc.signer_name}<br/><small>{new Date(doc.signed_at).toLocaleString()}</small></p><a className="row-link" target="_blank" rel="noreferrer" href={'/api/departures?document='+encodeURIComponent(doc.id)}>View / print signed form ↗</a></>:<><p>Awaiting IT sign-off</p>{pending.length>0&&<ul>{pending.map(p=><li key={p}>{p}</li>)}</ul>}{data.canSign&&<button className="primary" disabled={busy||pending.length>0} onClick={()=>{setError('');setSign({employee:e,type})}}>Sign {type.toLowerCase()} form</button>}</>}</section>})}</div>{e.status==='Offboarding'&&<p>After both forms are signed, complete offboarding from the employee profile.</p>}</article>)}{!rows.length&&<p>No departed employees match this selection.</p>}{!employeeId&&<div className="detail-actions"><button className="secondary" disabled={current===1} onClick={()=>setPage(current-1)}>Previous</button><span>Page {current} of {pages} · {rows.length} employees</span><button className="secondary" disabled={current===pages} onClick={()=>setPage(current+1)}>Next</button></div>}
 <Dialog open={!!sign} onOpenChange={v=>{if(!v&&!busy)setSign(null)}}><DialogContent className="!max-w-xl"><DialogTitle>IT sign-off · {sign?.type}</DialogTitle><DialogDescription>Sign {sign?.employee.name}’s {sign?.type.toLowerCase()} form as {data.signer.name} ({data.signer.username}). This saves an immutable checklist and electronic IT sign-off.</DialogDescription><form onSubmit={e=>{e.preventDefault();void signForm(e.currentTarget)}}><label className="field">IT remarks<textarea name="note" maxLength={2000} placeholder="Condition on return, handover notes, or clearance reference"/></label><label className="field">Your current password<input name="password" type="password" autoComplete="current-password" required maxLength={128}/></label><label className="sign-confirm"><input name="confirmed" type="checkbox" required/> {sign?.type==='Turnover'?'I confirm IT received the equipment and accessories listed in this employee’s record, or none were issued.':'I confirm all equipment, software and account obligations are resolved and I authorize this IT clearance.'}</label>{error&&<p className="error" role="alert">{error}</p>}<div className="form-actions"><button type="button" className="secondary" disabled={busy} onClick={()=>setSign(null)}>Cancel</button><button className="primary" disabled={busy}>{busy?'Signing…':'Sign as '+data.signer.name}</button></div></form></DialogContent></Dialog></section>;
}

