'use client';
import {EmployeeBrandField} from '@/components/employee-brand-field';
import {EmploymentTypeField} from './employment-type-field';
import {useState,type FormEvent} from 'react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from './ui/dialog';
type Employee={brand?:string;employment_type?:string;external_company?:string;internal_sponsor?:string;id:string;name:string;code:string;email:string;department:string;role:string;start_date:string};
export function EditEmployee({employee,refresh}:{employee:Employee;refresh:()=>Promise<void>}){
 const [open,setOpen]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('');
 async function save(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError('');try{const r=await fetch('/api/records',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...Object.fromEntries(new FormData(e.currentTarget)),action:'editEmployee',id:employee.id})});const d=await r.json() as {error?:string};if(!r.ok)throw Error(d.error||'Could not save employee');await refresh();setOpen(false)}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 return <><button className="secondary" onClick={()=>{setError('');setOpen(true)}}>Edit employee</button><Dialog open={open} onOpenChange={v=>{if(!busy)setOpen(v)}}><DialogContent><DialogTitle>Edit employee</DialogTitle><DialogDescription>Update this existing profile, including a surname change. Linked assets, accounts and documents remain attached. Changing the work email does not rename external accounts.</DialogDescription><form onSubmit={save}><div className="form-grid">{([['name','Full name (including surname)'],['code','Employee ID'],['email','Work email'],['role','Job title'],['start_date','Start date']] as const).map(([key,label])=><label className="field" key={key}>{label}<input name={key} defaultValue={employee[key]} type={key==='email'?'email':key==='start_date'?'date':'text'} required={key!=='start_date'} maxLength={200}/></label>)}<EmployeeBrandField value={employee.brand} department={employee.department}/><EmploymentTypeField value={employee.employment_type} company={employee.external_company} sponsor={employee.internal_sponsor}/></div>{error&&<p role="alert" className="error">{error}</p>}<div className="form-actions"><button type="button" className="secondary" disabled={busy} onClick={()=>setOpen(false)}>Cancel</button><button className="primary" disabled={busy}>{busy?'Saving…':'Save employee'}</button></div></form></DialogContent></Dialog></>
}
