'use client';
import {useState} from 'react';
import {Laptop,KeyRound,Package,Search,AppWindow} from 'lucide-react';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {provisionedItems,type ProvisionedAssignment} from '@/lib/provisioned-items';
import type {InventoryAsset} from '@/lib/asset-types';
import type {AccountRequest} from '@/lib/account-types';
import type {KitTask} from '@/lib/kit-types';
export function EmployeeProvisioned({employeeId,assets,assignments,requests,tasks}:{employeeId:string;assets:InventoryAsset[];assignments:ProvisionedAssignment[];requests:AccountRequest[];tasks:KitTask[]}){const [search,setSearch]=useState(''),[category,setCategory]=useState('All categories');const items=provisionedItems(employeeId,assets,assignments,requests,tasks),active=items.filter(i=>i.active),history=items.filter(i=>!i.active);const categories=['Hardware','Accessories','Accounts & access','Software & licenses'];const icons=[Laptop,Package,KeyRound,AppWindow];function list(current:boolean){const rows=items.filter(i=>i.active===current&&(category==='All categories'||i.category===category)&&`${i.name} ${i.identifier} ${i.detail}`.toLowerCase().includes(search.toLowerCase()));return rows.length?<div>{rows.map(i=>{const Icon=icons[categories.indexOf(i.category)]||Package;return <article className="provisioned-row" key={i.id}><span className="asset-icon"><Icon size={19}/></span><div className="provisioned-description"><strong>{i.name}{i.quantity>1&&<span className="badge ml-2">× {i.quantity}</span>}</strong><span>{i.identifier||i.category}</span>{i.detail&&<small>{i.detail}</small>}</div><div className="provisioned-state"><span className={'badge '+(i.active?'Active':'')}>{i.status}</span><small>{i.date?i.date.slice(0,10):''}</small></div></article>})}</div>:<div className="empty"><Package size={27}/><h3>{search||category!=='All categories'?'No matching items':current?'No items provisioned yet':'No cleared items yet'}</h3><p>{search?'Try an asset name, email, or tag.':current?'Completed account creation, equipment assignments, and issued kit items will appear here.':'Returned equipment and deactivated access will appear here.'}</p></div>}
return <section className="provisioned-panel"><div className="section-head"><h2>All provisioned items</h2><span className="badge">{active.length} current records</span></div><p className="mb-4">Equipment, accessories, accounts, and access linked to this employee.</p><div className="provisioned-summary">{categories.map((c,n)=>{const Icon=icons[n];return <div key={c}><Icon size={17}/><strong>{active.filter(i=>i.category===c).length}</strong><small>{c}</small></div>})}</div><div className="toolbar mt-5"><div className="search"><Search size={16}/><input aria-label="Search employee items" placeholder="Search laptop, Gmail, Teams, email, or asset tag…" value={search} onChange={e=>setSearch(e.target.value)}/></div><Select value={category} onValueChange={v=>setCategory(String(v))}><SelectTrigger aria-label="Filter provisioned category" className="min-h-10 bg-white"><SelectValue/></SelectTrigger><SelectContent>{['All categories',...categories].map(c=><SelectItem key={c} value={c}>{c}</SelectItem>)}</SelectContent></Select></div><Tabs defaultValue="current"><TabsList><TabsTrigger value="current" className="px-3">Current ({active.length})</TabsTrigger><TabsTrigger value="history" className="px-3">Returned / deactivated ({history.length})</TabsTrigger></TabsList><TabsContent value="current">{list(true)}</TabsContent><TabsContent value="history">{list(false)}</TabsContent></Tabs></section>}
