'use client';
import {useState} from 'react';
import {Laptop,KeyRound,Package,Search,AppWindow} from 'lucide-react';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {offboardingAction,provisionedItems,type ProvisionedAssignment} from '@/lib/provisioned-items';
import type {InventoryAsset} from '@/lib/asset-types';
import type {AccountRequest} from '@/lib/account-types';
import type {KitTask} from '@/lib/kit-types';
export function EmployeeProvisioned({employeeId,assets,assignments,requests,tasks}:{employeeId:string;assets:InventoryAsset[];assignments:ProvisionedAssignment[];requests:AccountRequest[];tasks:KitTask[]}){const [search,setSearch]=useState(''),[category,setCategory]=useState('All categories');const items=provisionedItems(employeeId,assets,assignments,requests,tasks),active=items.filter(i=>i.active),history=items.filter(i=>!i.active);const pending=requests.filter(r=>r.employee_id===employeeId&&['Submitted','Approved'].includes(r.status));const incomplete=requests.filter(r=>r.employee_id===employeeId&&r.status==='Active'&&(!r.purpose?.trim()||!r.account_role||r.account_role==='Unspecified'));const borrowed=assets.filter(a=>a.borrow_employee_id===employeeId&&a.borrow_status==='Reserved');const categories=['Hardware','Accessories','Accounts & access','Software & licenses','Temporary borrowing'];const icons=[Laptop,Package,KeyRound,AppWindow,Package];function list(current:boolean){const rows=items.filter(i=>i.active===current&&(category==='All categories'||i.category===category)&&`${i.name} ${i.identifier} ${i.detail}`.toLowerCase().includes(search.toLowerCase()));return rows.length?<div>{rows.map(i=>{const Icon=icons[categories.indexOf(i.category)]||Package;return <article className="provisioned-row" key={i.id}><span className="asset-icon"><Icon size={19}/></span><div className="provisioned-description"><strong>{i.name}{i.quantity>1&&<span className="badge ml-2">× {i.quantity}</span>}</strong><span>{i.identifier||i.category}</span>{i.detail&&<small>{i.detail}</small>}{i.active&&<small><b>Offboarding:</b> {offboardingAction(i)}</small>}{i.category==='Accounts & access'&&<small>Verification source: IT record · provider status is not synchronized</small>}</div><div className="provisioned-state"><span className={'badge '+(i.active?'Active':'')}>{i.status}</span><small>{i.date?i.date.slice(0,10):''}</small></div></article>})}</div>:<div className="empty"><Package size={27}/><h3>{search||category!=='All categories'?'No matching items':current?'No items provisioned yet':'No cleared items yet'}</h3><p>{search?'Try an asset name, email, or tag.':current?'Completed account creation, equipment assignments, and issued kit items will appear here.':'Returned equipment and deactivated access will appear here.'}</p></div>}
return <section className="provisioned-panel"><div className="section-head"><h2>Currently provisioned</h2><span className="badge">{active.length} current records</span></div><p className="mb-4">Current equipment, accessories, accounts, licenses and borrowed items. Each record shows its required clearance action. Pending requests and reservations are separate.</p>{(pending.length>0||incomplete.length>0)&&<div className="notice"><strong>Account follow-up</strong>{pending.map(r=><p key={r.id}>{r.provider} · {r.username} · {r.status} — complete or cancel this request before clearance.</p>)}{incomplete.map(r=><p key={r.id}>{r.username} — record its primary/secondary designation and business purpose in Account Requests.</p>)}</div>}{borrowed.length>0&&<div className="notice"><strong>Reservations awaiting release</strong>{borrowed.map(a=><p key={a.id}>{a.tag} — {a.name} · {a.borrow_status}. Return the item or cancel the reservation in Temporary Borrowing before clearance.</p>)}</div>}<div className="provisioned-summary">{categories.map((c,n)=>{const Icon=icons[n];return <div key={c}><Icon size={17}/><strong>{active.filter(i=>i.category===c).length}</strong><small>{c}</small></div>})}</div><div className="toolbar mt-5"><div className="search"><Search size={16}/><input aria-label="Search employee items" placeholder="Search laptop, Gmail, Teams, email, or asset tag…" value={search} onChange={e=>setSearch(e.target.value)}/></div><Select value={category} onValueChange={v=>setCategory(String(v))}><SelectTrigger aria-label="Filter provisioned category" className="min-h-10 bg-card"><SelectValue/></SelectTrigger><SelectContent>{['All categories',...categories].map(c=><SelectItem key={c} value={c}>{c}</SelectItem>)}</SelectContent></Select></div><Tabs defaultValue="current"><TabsList><TabsTrigger value="current" className="px-3">Current ({active.length})</TabsTrigger><TabsTrigger value="history" className="px-3">Returned / deactivated ({history.length})</TabsTrigger></TabsList><TabsContent value="current">{list(true)}</TabsContent><TabsContent value="history">{list(false)}</TabsContent></Tabs></section>}
