'use client';
import {useState} from 'react';
type Employee={id:string;name:string;code:string;department:string;start_date:string;end_date?:string|null};
type Event={id:string;employee_id:string;message:string;created_at:string};
export function LifecycleHistory({kind,employees,events,onEmployee}:{kind:string;employees:Employee[];events:Event[];onEmployee:(id:string)=>void}){
 const [query,setQuery]=useState(''),[year,setYear]=useState('All years'),[page,setPage]=useState(1);
 const records=events.filter(e=>e.message.endsWith(' completed '+kind.toLowerCase())).map(e=>({...e,person:employees.find(p=>p.id===e.employee_id)})).sort((a,b)=>b.created_at.localeCompare(a.created_at));
 const years=Array.from(new Set(records.map(r=>r.created_at.slice(0,4)))).sort().reverse();
 const rows=records.filter(r=>(year==='All years'||r.created_at.startsWith(year))&&`${r.person?.name} ${r.person?.code} ${r.person?.department} ${r.message}`.toLowerCase().includes(query.toLowerCase()));const pages=Math.max(1,Math.ceil(rows.length/8)),current=Math.min(page,pages);
 return <section className="panel"><h2>Completed {kind.toLowerCase()} history</h2><p>Based on recorded completion events. Imported employee status alone is not proof of a completed workflow. Open the employee to review linked items and forms.</p><div className="toolbar my-4"><input aria-label="Search completed employees" placeholder="Search employee or department" value={query} onChange={e=>{setQuery(e.target.value);setPage(1)}}/><select aria-label="Completion year" value={year} onChange={e=>{setYear(e.target.value);setPage(1)}}><option>All years</option>{years.map(y=><option key={y}>{y}</option>)}</select></div><div className="access-table"><table><thead><tr><th>Employee</th><th>Department</th><th>{kind==='Onboarding'?'Employment start':'Last working day'}</th><th>Recorded completion</th><th>Details</th></tr></thead><tbody>{rows.slice((current-1)*8,current*8).map(r=><tr key={r.id}><td>{r.person?.name||'Employee unavailable'}<small>{r.person?.code}</small></td><td>{r.person?.department||'—'}</td><td>{(kind==='Onboarding'?r.person?.start_date:r.person?.end_date)||'Not recorded'}</td><td>{new Date(r.created_at).toLocaleString()}<small>{r.message}</small></td><td><button disabled={!r.person} onClick={()=>onEmployee(r.employee_id)}>View employee</button></td></tr>)}</tbody></table></div>{!rows.length&&<p>No recorded completions match this view.</p>}<div className="detail-actions"><button className="secondary" disabled={current===1} onClick={()=>setPage(current-1)}>Previous</button><span>{rows.length} records · Page {current} of {pages}</span><button className="secondary" disabled={current===pages} onClick={()=>setPage(current+1)}>Next</button></div></section>
}
