'use client';
import {useEffect,useState} from 'react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from './ui/dialog';
type Account={id:string;name:string;username:string;email:string;role:string;active:number;employee_id:string|null;must_change_password:number};
type AccessData={users:Account[];employees:{id:string;name:string;code:string}[];audit:{id:string;created_at:string;actor_username:string;action:string}[]};
export function ManageAccess({role}:{role:string}){
 const [data,setData]=useState<AccessData>({users:[],employees:[],audit:[]}),[search,setSearch]=useState(''),[page,setPage]=useState(1),[mode,setMode]=useState(''),[selected,setSelected]=useState<Account|null>(null),[error,setError]=useState(''),[message,setMessage]=useState(''),[secret,setSecret]=useState(''),[busy,setBusy]=useState(false);
 async function load(){const r=await fetch('/api/users');const d=await r.json() as AccessData & {error?:string};if(!r.ok)throw Error(d.error);setData(d)}
 useEffect(()=>{void load().catch(e=>setError(e.message))},[]);
 const rows=data.users.filter(u=>`${u.name} ${u.username} ${u.email}`.toLowerCase().includes(search.toLowerCase())),pages=Math.max(1,Math.ceil(rows.length/8)),current=Math.min(page,pages);
 function open(action:string,u:Account|null=null){setSelected(u);setMode(action);setError('');setSecret('')}
 async function save(body:Record<string,unknown>){setBusy(true);setError('');setSecret('');try{const r=await fetch('/api/users',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const b=await r.json() as {error?:string;temporaryPassword?:string};if(!r.ok)throw Error(b.error);await load();setMode('');setMessage('Account saved.');if(b.temporaryPassword)setSecret(b.temporaryPassword)}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 return <main className="access-management"><h1>Manage access</h1><p>{role==='super_admin'?'Manage Super Admin, Admin and User logins.':'Manage User logins. Administrator accounts are managed by a Super Admin.'} Email is optional.</p><button className="primary" onClick={()=>open('create')}>Add account</button><label className="field">Search accounts<input value={search} onChange={e=>{setSearch(e.target.value);setPage(1)}}/></label>{message&&<p role="status">{message}</p>}{error&&!mode&&<p className="error" role="alert">{error}</p>}{secret&&<div className="notice"><strong>Temporary password — copy before dismissing</strong><pre>{secret}</pre><p>A password change is required at first sign-in.</p><button className="secondary" onClick={()=>setSecret('')}>Dismiss</button></div>}<div className="access-table"><table><thead><tr><th>Name / username</th><th>Role / status</th><th>Employee</th><th>Actions</th></tr></thead><tbody>{rows.slice((current-1)*8,current*8).map(u=><tr key={u.id}><td>{u.name}<small>{u.username} · {u.email||'No email'}</small></td><td>{u.role.replace('_',' ')}<small>{u.active?'Active':'Disabled'}{u.must_change_password?' · Password change required':''}</small></td><td>{data.employees.find(e=>e.id===u.employee_id)?.name||(u.employee_id?'Departing employee':'Not linked')}</td><td><button onClick={()=>open('edit',u)}>Edit</button><button onClick={()=>open('setEmployee',u)}>Link employee</button><button onClick={()=>open('update',u)}>Role / access</button><button onClick={()=>open('resetPassword',u)}>Reset password</button><button onClick={()=>open('delete',u)}>Delete</button></td></tr>)}</tbody></table>{!rows.length&&<p>No accounts found.</p>}</div><div className="detail-actions"><button className="secondary" disabled={current===1} onClick={()=>setPage(current-1)}>Previous</button><span>Page {current} of {pages}</span><button className="secondary" disabled={current===pages} onClick={()=>setPage(current+1)}>Next</button></div>{role==='super_admin'&&<details><summary>Recent security activity</summary>{data.audit.map(a=><p key={a.id}>{a.created_at} · {a.actor_username||'System / deleted login'} · {a.action}</p>)}</details>}
 <Dialog open={!!mode} onOpenChange={v=>{if(!v&&!busy)setMode('')}}><DialogContent className="!max-w-xl max-h-[85vh] overflow-auto"><DialogTitle>{mode==='create'?'Create account':mode==='delete'?'Delete login account':mode==='resetPassword'?'Reset password':'Edit account'}</DialogTitle><DialogDescription>{mode==='delete'?`Delete login ${selected?.username}? Sign-in and existing sessions will be removed. Employee records and signed documents remain.`:mode==='resetPassword'?'Generate a new temporary password and revoke existing sessions.':mode==='setEmployee'?'Choose the employee this login may view. Existing sessions will be revoked.':'Update login details. Users must sign in again after account changes.'}</DialogDescription><form key={mode+selected?.id} onSubmit={e=>{e.preventDefault();const fields=Object.fromEntries(new FormData(e.currentTarget));void save({...fields,action:mode,id:selected?.id,...(mode==='update'?{active:fields.active==='on'}:{})})}}><div className="form-grid">{['create','edit'].includes(mode)&&<><label className="field">Name<input name="name" defaultValue={selected?.name||''} required maxLength={200}/></label><label className="field">Username<input name="username" defaultValue={selected?.username||''} required minLength={3} maxLength={64} pattern="[a-zA-Z0-9._-]+"/></label><label className="field">Email (optional)<input name="email" type="email" defaultValue={selected?.email||''}/></label></>}{['create','update'].includes(mode)&&<label className="field">Role<select name="role" defaultValue={selected?.role||'user'}>{(role==='super_admin'?['user','admin','super_admin']:['user']).map(r=><option key={r} value={r}>{r.replace('_',' ')}</option>)}</select></label>}{['create','setEmployee'].includes(mode)&&<label className="field full">Linked employee<select name="employee_id" defaultValue={selected?.employee_id||''}><option value="">Not linked</option>{data.employees.map(e=><option key={e.id} value={e.id}>{e.name} · {e.code}</option>)}</select></label>}{mode==='update'&&<label className="field">Allow sign-in<input name="active" type="checkbox" defaultChecked={!!selected?.active}/></label>}</div>{error&&<p className="error" role="alert">{error}</p>}<div className="form-actions"><button type="button" className="secondary" disabled={busy} onClick={()=>setMode('')}>Cancel</button><button className="primary" disabled={busy}>{busy?'Saving…':mode==='delete'?'Delete login':mode==='resetPassword'?'Reset password':'Save account'}</button></div></form></DialogContent></Dialog></main>;
}
