'use client';
import {useState,useEffect,type FormEvent} from 'react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from './ui/dialog';
type Review={id:string;decision:string;manager_name:string;approved_on:string;recipient_id:string;recipient_name:string;instructions:string;evidence_reference:string;evidence_name:string;completed_at:string;completed_by:string;completion_note:string;version:number};
type Row={changed:boolean;designation?:string;key:string;name:string;identifier:string;purpose:string;status:string;review:Review|null};
type Data={rows:Row[];recipients:{id:string;name:string;code:string}[];locked:boolean;history:{id:string;actor_name:string;action:string;created_at:string;snapshot:string}[]};
export function ManagerHandovers({employeeId,onChange}:{employeeId:string;onChange:()=>Promise<void>}){
 const [data,setData]=useState<Data|null>(null),[error,setError]=useState(''),[editing,setEditing]=useState<Row|null>(null),[completing,setCompleting]=useState(false),[decision,setDecision]=useState('Transfer'),[busy,setBusy]=useState(false);
 async function load(){const r=await fetch('/api/manager-handovers?employeeId='+encodeURIComponent(employeeId));const d=await r.json() as Data & {error?:string};if(!r.ok)throw Error(d.error);setData(d)}
 useEffect(()=>{load().catch(e=>setError(e.message))},[employeeId]);
 async function save(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!editing)return;setBusy(true);setError('');try{const form=new FormData(e.currentTarget);form.set('action',completing?'complete':'review');form.set('employeeId',employeeId);form.set('source_key',editing.key);form.set('version',String(editing.review?.version||0));const r=await fetch('/api/manager-handovers',{method:'POST',body:form});const d=await r.json() as {error?:string};if(!r.ok)throw Error(d.error);await load();await onChange();setEditing(null)}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 const pending=data?.rows.filter(r=>r.changed||!r.review||r.review.decision==='Transfer'&&!r.review.completed_at).length||0;
 return <section className="employee-kit mt-4"><h3>Manager clearance — Account handover</h3><p>IT records the manager’s approval and confirms transfer of business resources. Account deactivation is handled separately and should follow the departure schedule.</p>{error&&!editing&&<p role="alert" className="error">{error}</p>}{!data?<p>Loading account handovers…</p>:<><p>{pending} pending · {data.rows.length} account/access items</p>{!data.rows.length&&<p>No provisioned accounts or system access recorded. Confirm the employee’s account register is complete before clearance.</p>}{data.rows.map(row=>{const r=row.review;return <article className="panel p-4 mb-3" key={row.key}><strong>{row.name}</strong><p>{row.identifier} · {row.status}</p><p>{row.designation} {row.purpose}</p>{row.changed&&<p className="error">Account details changed. Manager approval needs review.</p>}<span className="badge">{!r?'Awaiting manager approval':r.completed_at?'Handover completed':r.decision==='No handover'?'No handover required':'Approved for handover'}</span>{r&&<><p>Manager: {r.manager_name} · Approved {r.approved_on}</p>{r.recipient_name&&<p>Receiving employee: {r.recipient_name}</p>}<p>{r.instructions}</p>{r.evidence_reference&&<p>Approval reference: {r.evidence_reference}</p>}{r.evidence_name&&<a className="row-link" href={'/api/manager-handovers?file='+encodeURIComponent(r.id)}>Download approval: {r.evidence_name}</a>}{r.completed_at&&<p>Completed by {r.completed_by} on {new Date(r.completed_at).toLocaleString()} · {r.completion_note}</p>}</>}{!data.locked&&(!r?.completed_at||row.changed)&&<div className="detail-actions"><button className="secondary" onClick={()=>{setError('');setEditing(row);setCompleting(false);setDecision(r?.decision||'Transfer')}}>{r?'Edit manager approval':'Record manager approval'}</button>{r?.decision==='Transfer'&&!row.changed&&!r.completed_at&&<button className="primary" onClick={()=>{setError('');setEditing(row);setCompleting(true)}}>Confirm IT handover</button>}</div>}</article>})}{data.history.length>0&&<details><summary>Handover audit history ({data.history.length})</summary>{data.history.map(h=>{const s=JSON.parse(h.snapshot);return <p key={h.id}>{new Date(h.created_at).toLocaleString()} · {h.actor_name} · {s.name} · {h.action==='complete'?'IT handover completed':s.review.decision+' approved by '+s.review.manager_name}</p>})}</details>}</>}
 <Dialog open={!!editing} onOpenChange={v=>{if(!v&&!busy)setEditing(null)}}><DialogContent className="!max-w-xl max-h-[90vh] overflow-auto"><DialogTitle>{completing?'Confirm IT handover':'Record manager approval'}</DialogTitle><DialogDescription>{editing?.name} · {editing?.identifier}. Approval is obtained outside the app and recorded by IT.</DialogDescription><form onSubmit={save}>{completing?<><label className="field">Completion details<textarea name="completion_note" required maxLength={2000} placeholder="Resources transferred and verification performed"/></label><label><input type="checkbox" name="confirmed" value="true" required/> IT completed the approved handover.</label></>:<><label className="field">Manager name<input name="manager_name" defaultValue={editing?.review?.manager_name||''} required maxLength={200}/></label><label className="field">Approval date<input type="date" name="approved_on" required defaultValue={editing?.review?.approved_on||''}/></label><label className="field">Manager decision<select name="decision" value={decision} onChange={e=>setDecision(e.target.value)}><option value="Transfer">Transfer business resources</option><option value="No handover">No handover required</option></select></label>{decision==='Transfer'&&<label className="field">Receiving employee<select name="recipient_id" defaultValue={editing?.review?.recipient_id||''} required><option value="">Choose an active employee</option>{data?.recipients.map(e=><option key={e.id} value={e.id}>{e.code} — {e.name}</option>)}</select></label>}<label className="field">{decision==='Transfer'?'Resources and handover instructions':'Reason no handover is required'}<textarea name="instructions" required maxLength={2000} defaultValue={editing?.review?.instructions||''}/></label><label className="field">Approval email / document reference<input name="evidence_reference" maxLength={2000} defaultValue={editing?.review?.evidence_reference||''}/></label><label className="field">Attach approval (PDF, JPG or PNG, up to 8 MB)<input type="file" name="file" accept="application/pdf,image/png,image/jpeg" disabled={!!editing?.review?.evidence_name}/></label><p>{editing?.review?.evidence_name?'Existing approval attachment is retained.':'Provide an attachment or an approval reference.'}</p></>}{error&&<p role="alert" className="error">{error}</p>}<div className="form-actions"><button type="button" className="secondary" disabled={busy} onClick={()=>setEditing(null)}>Cancel</button><button className="primary" disabled={busy}>{busy?'Saving…':completing?'Confirm completed':'Save approval'}</button></div></form></DialogContent></Dialog>
 </section>
}

