'use client';
import reasons from '@/lib/movement-reasons.json';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from './ui/dialog';
import {useEffect,useState,type FormEvent} from 'react';
type Movement={version:number;notes:string;id:string;movement_type:string;occurred_on:string;source_date:string;source_tag:string;matched_tag:string;source_employee:string;matched_employee:string;reason:string;allocated_to:string;source_sheet:string;source_row:number;review_note:string};
export function MovementHistory({assetId='',employeeId='',expanded=false}:{assetId?:string;employeeId?:string;expanded?:boolean}){
 const [editing,setEditing]=useState<Movement|null>(null),[saving,setSaving]=useState(false),[editError,setEditError]=useState('');
 async function saveEdit(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!editing)return;setSaving(true);setEditError('');try{const r=await fetch('/api/asset-movements',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...Object.fromEntries(new FormData(e.currentTarget)),id:editing.id,version:editing.version})});const d=await r.json() as {row:Movement;error?:string};if(!r.ok)throw Error(d.error||'Unable to save');setRows(old=>old.map(x=>x.id===editing.id?{...x,...d.row}:x));setEditing(null)}catch(e){setEditError((e as Error).message)}finally{setSaving(false)}}
 const [rows,setRows]=useState<Movement[]>([]),[error,setError]=useState(''),[loading,setLoading]=useState(true),[query,setQuery]=useState(''),[type,setType]=useState('Deployment'),[year,setYear]=useState('All years'),[review,setReview]=useState(false),[page,setPage]=useState(1);
 useEffect(()=>{let active=true;setLoading(true);fetch('/api/asset-movements?'+new URLSearchParams({assetId,employeeId})).then(async r=>{const data=await r.json() as {rows:Movement[];error?:string};if(!r.ok)throw Error(data.error||'Unable to load history');if(active){setRows(data.rows);setError('');}}).catch(e=>{if(active)setError(e.message);}).finally(()=>{if(active)setLoading(false);});return()=>{active=false}},[assetId,employeeId]);
 const yearOf=(r:Movement)=>/^\d{4}-\d{2}-\d{2}$/.test(r.occurred_on||'')?r.occurred_on.slice(0,4):'Unknown date';
 const years=Array.from(new Set(rows.map(yearOf).filter(y=>y!=='Unknown date'))).sort().reverse();
 const filtered=rows.filter(r=>r.movement_type===type&&(year==='All years'||yearOf(r)===year)&&(!review||r.review_note)&&[r.source_tag,r.matched_tag,r.source_employee,r.matched_employee,r.reason,r.source_sheet].join(' ').toLowerCase().includes(query.toLowerCase())).sort((a,b)=>(b.occurred_on||'').localeCompare(a.occurred_on||'')||b.source_row-a.source_row);
 const pages=Math.max(1,Math.ceil(filtered.length/8)),current=Math.min(page,pages);
 return <details open={expanded || undefined} className="panel p-4 my-4"><summary className="cursor-pointer font-semibold">Laptop deployment &amp; return history ({rows.length})</summary>
 <p className="my-3 text-sm">Imported historical records. These entries do not change current assignments or certify signed forms.</p>
 {error?<p role="alert">{error}</p>:loading?<p>Loading history…</p>:<>
 <div className="detail-actions" role="group" aria-label="History section">{['Deployment','Return'].map(t=><button type="button" key={t} aria-pressed={type===t} className={type===t?'primary':'secondary'} onClick={()=>{setType(t);setPage(1)}}>{t==='Deployment'?'Deployments':'Returns'} ({rows.filter(r=>r.movement_type===t&&(year==='All years'||yearOf(r)===year)).length})</button>)}</div><div className="flex flex-wrap items-end gap-3 my-3"><input aria-label="Search movement history" placeholder="Search control number or employee" value={query} onChange={e=>{setQuery(e.target.value);setPage(1)}}/><label className="field">Year<select aria-label="Movement year" value={year} onChange={e=>{setYear(e.target.value);setPage(1)}}><option>All years</option>{years.map(y=><option key={y}>{y}</option>)}{rows.some(r=>yearOf(r)==='Unknown date')&&<option>Unknown date</option>}</select></label><label><input type="checkbox" checked={review} onChange={e=>{setReview(e.target.checked);setPage(1)}}/> Needs review</label></div>
 <div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr>{['Date / action','Control number','Employee','Reason / allocation','Source / review','Actions'].map(h=><th className="p-2 text-left" key={h}>{h}</th>)}</tr></thead><tbody>{filtered.slice((current-1)*8,current*8).map(r=><tr key={r.id}><td className="p-2">{r.occurred_on||r.source_date||'Unknown date'}<br/>{r.movement_type}</td><td className="p-2">{r.matched_tag||r.source_tag||'Unmatched'}</td><td className="p-2">{r.matched_employee||r.source_employee||'Unrecorded'}</td><td className="p-2">{r.reason||'—'}{r.allocated_to&&<div>Allocation note: {r.allocated_to}</div>}</td><td className="p-2">{r.source_sheet} · row {r.source_row}{r.review_note&&<div className="text-amber-800 dark:text-amber-300">{r.review_note}</div>}</td><td className="p-2"><button className="secondary" onClick={()=>{setEditing(r);setEditError('')}}>Edit</button></td></tr>)}</tbody></table></div>
 {!filtered.length&&<p>No matching history.</p>}<div className="flex items-center gap-3 mt-3"><button type="button" className="secondary" disabled={current===1} onClick={()=>setPage(current-1)}>Previous</button><span>Page {current} of {pages} · {filtered.length} records</span><button type="button" className="secondary" disabled={current===pages} onClick={()=>setPage(current+1)}>Next</button></div></>}
 <Dialog open={!!editing} onOpenChange={v=>{if(!v&&!saving)setEditing(null)}}><DialogContent className="max-h-[90vh] overflow-auto"><DialogTitle>Edit {editing?.movement_type.toLowerCase()} record</DialogTitle><DialogDescription>Correct this historical record. This does not change current custody, complete offboarding, or approve a gadget loan.</DialogDescription>{editing&&<form key={editing.id} onSubmit={saveEdit}><p>{editing.matched_tag||editing.source_tag} · {editing.matched_employee||editing.source_employee}</p><label className="field">Movement date<input name="occurred_on" type="date" defaultValue={editing.occurred_on} required/></label><label className="field">Reason<select name="reason" defaultValue={(reasons[editing.movement_type as keyof typeof reasons]||[]).includes(editing.reason)?editing.reason:''} required><option value="">Choose reason</option>{(reasons[editing.movement_type as keyof typeof reasons]||[]).map(x=><option key={x}>{x}</option>)}</select></label><p>Previous reason: {editing.reason||'Not recorded'}</p><label className="field">Explanation / eligibility details<textarea name="notes" defaultValue={editing.notes} maxLength={2000}/></label><label className="field">Allocation note<input name="allocated_to" defaultValue={editing.allocated_to} maxLength={2000}/></label><label className="field">Why are you correcting this record?<textarea name="correction_reason" required maxLength={2000}/></label>{editError&&<p role="alert" className="error">{editError}</p>}<div className="form-actions"><button type="button" className="secondary" disabled={saving} onClick={()=>setEditing(null)}>Cancel</button><button className="primary" disabled={saving}>{saving?'Saving…':'Save correction'}</button></div></form>}</DialogContent></Dialog>
 </details>
}
