'use client';
import {useState} from 'react';
import {AssetFields} from './asset-panel';
import type {InventoryAsset} from '@/lib/asset-types';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from './ui/dialog';
type Employee={id:string;code:string;name:string;email:string;department:string;role:string;start_date:string;status:string};
export function RecordManagement({employees,assets,refresh}:{employees:Employee[];assets:InventoryAsset[];refresh:()=>Promise<void>}){
 const [tab,setTab]=useState('employees'),[search,setSearch]=useState(''),[page,setPage]=useState(1),[mode,setMode]=useState(''),[selected,setSelected]=useState(''),[kind,setKind]=useState('Hardware'),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState('');
 const employee=employees.find(e=>e.id===selected),asset=assets.find(a=>a.id===selected);
 const records=tab==='employees'?employees:assets.filter(a=>a.kind!=='Account');
 const rows=records.filter(r=>Object.values(r).some(v=>String(v).toLowerCase().includes(search.toLowerCase()))),pages=Math.max(1,Math.ceil(rows.length/8)),current=Math.min(page,pages);
 function open(action:string,id=''){setSelected(id);setMode(action);setError('');setKind(assets.find(a=>a.id===id)?.kind||'Hardware')}
 async function save(form:HTMLFormElement){setBusy(true);setError('');const fields=Object.fromEntries(new FormData(form));const action=mode==='delete'?(tab==='employees'?'deleteEmployee':'deleteAsset'):tab==='employees'?(selected?'editEmployee':'employee'):(selected?'editAsset':'asset');
 try{const r=await fetch(['/api/records','/api/workspace'][['employee','asset','editAsset'].includes(action)?1:0],{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...fields,action,id:selected,assetId:selected,kind,startDate:fields.start_date})});const b=await r.json() as {error?:string};if(!r.ok)throw Error(b.error);await refresh();setMode('');setMessage(mode==='delete'?'Unused record deleted.':'Record saved.')}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 return <section className="record-management"><div className="detail-actions"><button className={tab==='employees'?'primary':'secondary'} onClick={()=>{setTab('employees');setPage(1);setSearch('')}}>Employees</button><button className={tab==='assets'?'primary':'secondary'} onClick={()=>{setTab('assets');setPage(1);setSearch('')}}>Assets</button><button className="primary" onClick={()=>open('edit')}>Add {tab==='employees'?'employee':'asset'}</button></div><p>Create test records using a TEST- prefix. Delete removes unused records only; assignment, maintenance, and signed document history is retained.</p>{message&&<p role="status" className="success">{message}</p>}<label className="field">Search {tab}<input value={search} onChange={e=>{setSearch(e.target.value);setPage(1)}}/></label><div className="access-table"><table><thead><tr><th>Name</th><th>{tab==='employees'?'Employee ID / department':'Asset tag / type'}</th><th>Status</th><th>Actions</th></tr></thead><tbody>{rows.slice((current-1)*8,current*8).map(r=><tr key={r.id}><td>{r.name}</td><td>{'code' in r?`${r.code} · ${r.department}`:`${r.tag} · ${r.kind}`}</td><td>{'status' in r?r.status:r.state}</td><td><button onClick={()=>open('edit',r.id)}>Edit</button><button onClick={()=>open('delete',r.id)}>Delete unused record</button></td></tr>)}</tbody></table>{!rows.length&&<p>No matching records.</p>}</div><div className="detail-actions"><button className="secondary" disabled={current===1} onClick={()=>setPage(current-1)}>Previous</button><span>Page {current} of {pages} · {rows.length} records</span><button className="secondary" disabled={current===pages} onClick={()=>setPage(current+1)}>Next</button></div>
 <Dialog open={!!mode} onOpenChange={v=>{if(!v&&!busy)setMode('')}}><DialogContent className="!max-w-2xl max-h-[85vh] overflow-auto"><DialogTitle>{mode==='delete'?'Delete unused record':selected?'Edit record':'Create record'}</DialogTitle><DialogDescription>{mode==='delete'?`Delete ${employee?.name||asset?.name}? This cannot be undone. Records with operational links cannot be deleted.`:'Save employee or inventory details. Employment status changes through onboarding and offboarding.'}</DialogDescription><form key={`${tab}-${selected}-${mode}`} onSubmit={e=>{e.preventDefault();void save(e.currentTarget)}}>{mode!=='delete'&&<div className="form-grid">{tab==='employees'?(['name','code','email','department','role','start_date'] as const).map(field=><label className="field" key={field}>{({name:'Full name',code:'Employee ID',email:'Work email',department:'Department',role:'Job title',start_date:'Start date'})[field]}<input name={field} type={field==='email'?'email':field==='start_date'?'date':'text'} defaultValue={employee?.[field]||''} required={field!=='start_date'||!selected} maxLength={200}/></label>):<><label className="field full">Asset type<select value={kind} disabled={!!selected} onChange={e=>setKind(e.target.value)}><option>Hardware</option><option>Software</option></select></label><AssetFields key={kind} kind={kind} asset={asset}/></>}</div>}{error&&<p className="error" role="alert">{error}</p>}<div className="form-actions"><button type="button" className="secondary" disabled={busy} onClick={()=>setMode('')}>Cancel</button><button className="primary" disabled={busy}>{busy?'Saving…':mode==='delete'?'Delete record':'Save record'}</button></div></form></DialogContent></Dialog></section>;
}
