import {handoverRows} from './manager-handover.mjs';
import {createHash,randomUUID} from 'node:crypto';
import {connection as db} from './database.mjs';
import {audit,HttpError} from './auth.mjs';
const queries={
 verifications:`SELECT v.id,a.tag AS control_number,a.name AS asset,v.status,v.expected AS recorded_snapshot,v.observed AS observed_snapshot,v.discrepancies,v.checked_at,v.checked_by_name,v.resolution,v.resolved_at,v.resolved_by FROM asset_verifications v JOIN assets a ON a.id=v.asset_id ORDER BY v.checked_at DESC,v.id`,
 inventory:`SELECT a.id,a.tag AS control_number,a.name,a.serial,a.kind,a.state,json_extract(a.details,'$.category') AS category,json_extract(a.details,'$.custodian') AS source_custodian,json_extract(a.details,'$.purchase_date') AS purchase_date,json_extract(a.details,'$.supplier') AS supplier,a.is_test,(SELECT group_concat(e.code||' - '||e.name,'; ') FROM assignments x JOIN employees e ON e.id=x.employee_id WHERE x.asset_id=a.id AND x.resolved_at IS NULL) AS assigned_to,(SELECT count(*) FROM maintenance m WHERE m.asset_id=a.id AND m.completed_date IS NULL) AS open_maintenance,(SELECT group_concat(b.status,'; ') FROM borrowing_items i JOIN borrowings b ON b.id=i.borrowing_id WHERE i.asset_id=a.id AND i.returned_at IS NULL AND b.status IN ('Reserved','Borrowed')) AS borrowing_status FROM assets a ORDER BY a.tag,a.id`,
 provisioning:`SELECT x.id,e.code AS employee_code,e.name AS employee,e.status AS employment_status,e.department,a.tag AS control_number,a.name AS asset,a.kind,x.identifier,x.assigned_at,x.resolved_at,x.resolution,e.is_test AS test_employee,a.is_test AS test_asset FROM assignments x JOIN employees e ON e.id=x.employee_id JOIN assets a ON a.id=x.asset_id ORDER BY e.code,x.assigned_at,x.id`,
 accounts:`SELECT r.id,e.code AS employee_code,e.name AS employee,e.status AS employment_status,e.department,r.provider,r.username,r.account_role,r.services,r.purpose,r.requester,r.source,r.reference,r.status,r.review_note,r.created_at,r.updated_at,e.is_test AS test_employee FROM account_requests r JOIN employees e ON e.id=r.employee_id ORDER BY e.code,r.provider,r.username,r.id`,
 offboarding:`SELECT e.id,e.code,e.name,e.department,e.status,e.end_date,e.departure_reason,e.is_test,(SELECT count(*) FROM assignments x WHERE x.employee_id=e.id AND x.resolved_at IS NULL) AS outstanding_assignments,(SELECT count(*) FROM account_requests r WHERE r.employee_id=e.id AND r.status IN ('Submitted','Approved','Active')) AS outstanding_accounts,(SELECT count(*) FROM kit_tasks k WHERE k.employee_id=e.id AND k.state='Provisioned' AND k.assignment_id IS NULL AND k.account_request_id IS NULL) AS outstanding_kit_items,(SELECT count(*) FROM borrowings b WHERE b.employee_id=e.id AND b.status IN ('Reserved','Borrowed')) AS open_borrowings,(SELECT count(*) FROM app_users u WHERE u.employee_id=e.id AND u.active=1) AS active_app_logins,(SELECT count(*) FROM departure_documents d WHERE d.employee_id=e.id AND d.type='Turnover') AS signed_turnover_records,(SELECT count(*) FROM departure_documents d WHERE d.employee_id=e.id AND d.type='Clearance') AS signed_clearance_records FROM employees e WHERE e.status IN ('Offboarding','Offboarded') ORDER BY e.end_date,e.code`,
 activity:`SELECT s.id,s.created_at,u.username AS actor_username,s.actor_id,s.action,s.target_id FROM security_events s LEFT JOIN app_users u ON u.id=s.actor_id ORDER BY s.created_at DESC,s.id`,
 accessories:`SELECT t.id,e.code AS employee_code,e.name AS employee,e.status AS employment_status,t.kind,t.label,t.quantity,t.state,t.completed_at,t.cleared_at,t.assignment_id,t.account_request_id FROM kit_tasks t JOIN employees e ON e.id=t.employee_id ORDER BY e.code,t.id`,
 review:`SELECT id,source_sheet,source_row,movement_type,source_tag,source_serial,source_employee,source_date,review_note FROM asset_movements WHERE review_note!='' ORDER BY source_sheet,source_row`
};
export function generateReport(type,actor){
 if(!['admin','super_admin'].includes(actor?.role))throw new HttpError(403,'Only IT administrators can generate audit reports.');
 if(!Object.hasOwn(queries,type))throw new HttpError(400,'Choose a valid report.');
 db.exec('BEGIN');let rows;
 try{rows=db.prepare(queries[type]).all();if(type==='offboarding')rows=rows.map(row=>{const items=handoverRows(row.id);return {...row,manager_handover_items:items.length,manager_handover_pending:items.filter(r=>r.changed||!r.review||r.review.decision==='Transfer'&&!r.review.completed_at).length}});db.exec('COMMIT')}catch(e){db.exec('ROLLBACK');throw e}
 const payload={report_id:randomUUID(),report:type,generated_at:new Date().toISOString(),generated_by:actor.username||actor.id,scope:'Current database snapshot; all records in this report, including test records where indicated. Not a historical as-of reconstruction.',row_count:rows.length,rows};
 const sha256=createHash('sha256').update(JSON.stringify(payload)).digest('hex');
 audit(actor.id,'audit_report_generated:'+type+':'+payload.report_id+':'+sha256,null);
 return {...payload,sha256,verification:'SHA-256 of UTF-8 JSON.stringify(payload), excluding sha256 and verification. This detects file changes; it is not a digital signature or proof of completeness.'};
}

