import {randomBytes,randomUUID,scrypt,timingSafeEqual,createHash} from 'node:crypto';
import {promisify} from 'node:util';
import {connection} from './database.mjs';
const derive=promisify(scrypt);
const hash=s=>createHash('sha256').update(s).digest('hex');
export function origin(){const url=new URL(process.env.APP_ORIGIN||'http://localhost:3000');if(process.env.NODE_ENV==='production'&&url.protocol!=='https:')throw Error('Production APP_ORIGIN must use HTTPS');return url.origin}
export function checkOrigin(request){if(request.headers.get('origin')!==origin())throw new HttpError(403,'Request origin denied.');}
export class HttpError extends Error{constructor(status,message){super(message);this.status=status}}
export function failure(e){const status=e instanceof HttpError?e.status:500;if(status===500)console.error('Request failed:',e.message);return Response.json({error:status===500?'Unable to complete request.':e.message},{status,headers:{'Cache-Control':'no-store'}})}
export function passwordRules(password){if(typeof password!=='string'||password.length<12||password.length>128)throw new HttpError(400,'Use a password of 12–128 characters.');}
export async function passwordHash(password){passwordRules(password);const salt=randomBytes(16).toString('hex');const result=await derive(password,salt,64,{N:32768,r:8,p:1,maxmem:64*1024*1024});return `scrypt$${salt}$${result.toString('hex')}`}
export async function verifyPassword(password,encoded){const [,salt,digest]=(encoded||'').split('$');if(!salt||!digest)return false;const actual=await derive(password,salt,64,{N:32768,r:8,p:1,maxmem:64*1024*1024});const expected=Buffer.from(digest,'hex');return expected.length===actual.length&&timingSafeEqual(expected,actual)}
export function publicUser(u){return {id:u.id,username:u.username,email:u.email,name:u.name,role:u.role,employee_id:u.employee_id,must_change_password:!!u.must_change_password}}
function sessionToken(request){return (request.headers.get('cookie')||'').split(';').map(s=>s.trim()).find(s=>s.startsWith('anchored_session='))?.slice(17)}
export function currentUser(request,allowPasswordChange=false){const token=sessionToken(request);if(!token||!/^[a-f0-9]{64}$/.test(token))throw new HttpError(401,'Please sign in.');const u=connection.prepare('SELECT u.* FROM app_users u JOIN app_sessions s ON s.user_id=u.id WHERE s.token_hash=? AND s.expires_at>? AND u.active=1').get(hash(token),Date.now());if(!u)throw new HttpError(401,'Session expired. Please sign in.');if(u.must_change_password&&!allowPasswordChange)throw new HttpError(403,'Change your temporary password first.');return u}
export function requireRole(request,roles){const user=currentUser(request);if(!roles.includes(user.role))throw new HttpError(403,'You do not have permission for this action.');return user}
export function cookie(token,maxAge=28800){return `anchored_session=${token}; Path=/; HttpOnly; SameSite=Strict; Max-Age=${maxAge}${new URL(origin()).protocol==='https:'?'; Secure':''}`}
export function startSession(userId){const token=randomBytes(32).toString('hex');connection.prepare('DELETE FROM app_sessions WHERE expires_at<=?').run(Date.now());connection.prepare('INSERT INTO app_sessions(token_hash,user_id,expires_at) VALUES(?,?,?)').run(hash(token),userId,Date.now()+28800000);return token}
export function logout(request){const token=sessionToken(request);if(token)connection.prepare('DELETE FROM app_sessions WHERE token_hash=?').run(hash(token));}
export function audit(actor,action,target){connection.prepare('INSERT INTO security_events(id,actor_id,action,target_id,created_at) VALUES(?,?,?,?,?)').run(randomUUID(),actor,action,target,new Date().toISOString())}
export function throttle(email){const now=Date.now();connection.exec('BEGIN IMMEDIATE');try{for(const key of ['global',hash(email)]){const r=connection.prepare('SELECT * FROM auth_limits WHERE key=?').get(key);const limit=key==='global'?120:10;if(r&&now-r.window_start<300000&&r.attempts>=limit)throw new HttpError(429,'Too many attempts. Try again in five minutes.');connection.prepare('INSERT INTO auth_limits(key,window_start,attempts) VALUES(?,?,1) ON CONFLICT(key) DO UPDATE SET window_start=excluded.window_start,attempts=?').run(key,r&&now-r.window_start<300000?r.window_start:now,r&&now-r.window_start<300000?r.attempts+1:1)}connection.exec('COMMIT')}catch(e){connection.exec('ROLLBACK');throw e}}
