export function csvCell(value:unknown){let text=String(value??'');if(/^[\s]*[=+\-@]/.test(text)||/^[\t\r\n]/.test(text))text="'"+text;return '"'+text.replaceAll('"','""')+'"';}
export function reportCsv(report:{report_id:string;report:string;generated_at:string;generated_by:string;sha256:string;scope:string;rows:Record<string,unknown>[]}){
 const keys=Object.keys(report.rows[0]||{});
 return '\uFEFF'+[['Report ID',report.report_id],['Report',report.report],['Generated UTC',report.generated_at],['Generated by',report.generated_by],['Snapshot JSON SHA-256',report.sha256],['Scope',report.scope],['Rows',report.rows.length],[],keys,...report.rows.map(r=>keys.map(k=>r[k]))].map(row=>row.map(csvCell).join(',')).join('\r\n');
}
