import type {InventoryAsset} from './asset-types';
import type {AccountRequest} from './account-types';
import type {KitTask} from './kit-types';
export type ProvisionedAssignment={id:string;employee_id:string;asset_id:string;identifier:string;assigned_at:string;resolved_at:string|null;resolution:string|null};
export type ProvisionedItem={id:string;name:string;category:string;identifier:string;detail:string;quantity:number;active:boolean;status:string;date:string};
export function provisionedItems(employeeId:string,assets:InventoryAsset[],assignments:ProvisionedAssignment[],requests:AccountRequest[],tasks:KitTask[]):ProvisionedItem[]{
const ownTasks=tasks.filter(t=>t.employee_id===employeeId);const result:ProvisionedItem[]=[];
for(const a of assignments.filter(a=>a.employee_id===employeeId)){const asset=assets.find(x=>x.id===a.asset_id);result.push({id:'assignment:'+a.id,name:asset?.name||'Asset record',category:asset?.kind==='Account'?'Accounts & access':asset?.kind==='Software'?'Software & licenses':'Hardware',identifier:asset?.kind==='Account'?a.identifier:[asset?.tag,asset?.serial].filter(Boolean).join(' · '),detail:asset?.kind==='Account'?'Legacy account assignment':a.identifier,quantity:1,active:!a.resolved_at,status:a.resolved_at?a.resolution||'Cleared':asset?.state==='Maintenance'?'Assigned · in maintenance':'Assigned',date:a.resolved_at||a.assigned_at});}
for(const r of requests.filter(r=>r.employee_id===employeeId&&['Active','Disabled'].includes(r.status))){result.push({id:'account:'+r.id,name:r.services||r.provider,category:'Accounts & access',identifier:r.username,detail:r.provider,quantity:1,active:r.status==='Active',status:r.status==='Active'?'Active':'Deactivated',date:r.updated_at});}
for(const t of ownTasks.filter(t=>!t.assignment_id&&!t.account_request_id&&['Provisioned','Cleared'].includes(t.state))){const parent=ownTasks.find(p=>p.id===t.parent_id);const account=parent?.account_request_id?requests.find(r=>r.id===parent.account_request_id):undefined;const assignment=parent?.assignment_id?assignments.find(a=>a.id===parent.assignment_id):undefined;const parentAsset=assignment?assets.find(a=>a.id===assignment.asset_id):undefined;result.push({id:'kit:'+t.id,name:t.label,category:t.kind==='Accessory'?'Accessories':t.kind==='Software'?'Software & licenses':'Accounts & access',identifier:account?.username||assignment?.identifier||'',detail:parent?`Included with ${parent.label}${parentAsset?.tag?' · '+parentAsset.tag:''}`:'Onboarding kit item',quantity:t.quantity,active:t.state==='Provisioned',status:t.state==='Cleared'?(t.kind==='Accessory'?'Returned':'Access removed'):(t.kind==='Accessory'?'Issued':'Enabled'),date:t.cleared_at||t.completed_at||''});}
return result;
}
