import {createHash,randomUUID} from 'node:crypto';
import {connection as db} from '@/server/database.mjs';
import {audit,checkOrigin,currentUser,failure,HttpError,requireRole,throttle,verifyPassword} from '@/server/auth.mjs';
import {blockers,departureSnapshot} from '@/server/departures.mjs';
const headers={'Cache-Control':'no-store'};
const escape=(v:unknown)=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
function printDocument(doc:Record<string,any>){const s=JSON.parse(doc.snapshot),e=s.employee;const list=(rows:Record<string,unknown>[],cols:string[])=>`<table><thead><tr>${cols.map(c=>`<th>${escape(c.replaceAll('_',' '))}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${cols.map(c=>`<td>${escape(r[c]||'—')}</td>`).join('')}</tr>`).join('')||`<tr><td colspan="${cols.length}">No items recorded.</td></tr>`}</tbody></table>`;
 return `<!doctype html><html lang="en"><head><meta charset="utf-8"><title>${escape(doc.type)} · ${escape(e.name)}</title><style>body{font:14px system-ui;color:#193641;max-width:1000px;margin:40px auto;padding:0 24px}h1{font-size:28px}table{border-collapse:collapse;width:100%;margin:20px 0}th,td{padding:9px;border:1px solid #cbd5da;text-align:left;overflow-wrap:anywhere}th{background:#eef3f4}section{break-inside:avoid;margin-top:25px}.signature{font-size:24px;font-style:italic}.muted{font-size:12px;color:#52646c;overflow-wrap:anywhere}button{padding:12px}@media print{button{display:none}body{margin:0;font-size:11px}thead{display:table-header-group}}</style></head><body><button onclick="window.print()">Print / Save as PDF</button><p>AnchorEd Asset Management · IT department</p><h1>${escape(doc.type)} Form</h1><p><strong>${escape(e.name)}</strong> · ${escape(e.code)}<br>${escape(e.department)} · ${escape(e.role)}<br>${escape(e.email)}</p><p>Last working day: ${escape(e.end_date)} · Departure reason: ${escape(e.departure_reason||'Not recorded')}</p><h2>Equipment and software</h2>${list(s.items,['name','tag','serial','kind','assigned_at','resolved_at','resolution'])}<h2>Account deactivation</h2>${list(s.accounts,['provider','username','status'])}<h2>Other provisioned items</h2>${list(s.accessories,['label','quantity','state','cleared_at'])}${s.manager_handovers?'<h2>Manager account handover clearance</h2>'+list(s.manager_handovers.map((r:any)=>({account:r.name,identifier:r.identifier,decision:r.review?.decision||'Not recorded',manager:r.review?.manager_name,approved_on:r.review?.approved_on,recipient:r.review?.recipient_name,instructions:r.review?.instructions,approval_reference:r.review?.evidence_reference,attachment:r.review?.evidence_name,completed_at:r.review?.completed_at,completed_by:r.review?.completed_by,completion_note:r.review?.completion_note})),['account','identifier','decision','manager','approved_on','recipient','instructions','approval_reference','attachment','completed_at','completed_by','completion_note']):''}<section><h2>IT team sign-off</h2><p>${doc.type==='Turnover'?'I confirm that equipment and accessories have been received by IT, or that no equipment was issued.':'I confirm that equipment, software and account obligations recorded in this checklist are cleared.'}</p><p>${escape(doc.note)}</p><p class="signature">${escape(doc.signer_name)}</p><p>Electronically signed by ${escape(doc.signer_username)} on ${escape(doc.signed_at)}.<br>Authenticated IT sign-off using the signer’s existing password.</p><p class="muted">Document ID: ${escape(doc.id)}<br>SHA-256: ${escape(doc.digest)}<br>This is a saved snapshot at sign-off. It is not a certificate-based digital signature.</p></section></body></html>`;
}
export async function GET(request:Request){try{
 const user=currentUser(request),q=new URL(request.url).searchParams,document=q.get('document'),employeeId=q.get('employeeId');
 if(document){const doc=db.prepare('SELECT * FROM departure_documents WHERE id=?').get(document);if(!doc||(user.role==='user'&&user.employee_id!==doc.employee_id))throw new HttpError(404,'Document not found.');return new Response(printDocument(doc),{headers:{...headers,'Content-Type':'text/html; charset=utf-8','X-Content-Type-Options':'nosniff'}})}
 if(user.role==='user'&&(!employeeId||employeeId!==user.employee_id))throw new HttpError(403,'Only your own documents are available.');
 const employees=db.prepare("SELECT * FROM employees WHERE status IN ('Offboarding','Offboarded')"+(employeeId?' AND id=?':'')+' ORDER BY end_date DESC,name').all(...(employeeId?[employeeId]:[]));
 const rows=employees.map((e:Record<string,string>)=>({...e,turnoverBlockers:blockers(e.id,'Turnover'),clearanceBlockers:blockers(e.id),documents:db.prepare('SELECT id,type,signer_name,signer_username,signed_at,note,digest FROM departure_documents WHERE employee_id=? ORDER BY signed_at').all(e.id)}));
 return Response.json({employees:rows,signer:{name:user.name,username:user.username},canSign:user.role!=='user'},{headers});
}catch(e){return failure(e)}}
export async function POST(request:Request){try{
 checkOrigin(request);const initial=requireRole(request,['super_admin','admin']),b=await request.json() as Record<string,unknown>;
 if(b.action!=='sign'||!['Turnover','Clearance'].includes(String(b.type))||typeof b.employeeId!=='string'||b.confirmed!==true||typeof b.password!=='string'||b.password.length>128||typeof b.note!=='string'||b.note.length>2000)throw new HttpError(400,'Confirm the checklist, enter your password and a note up to 2,000 characters.');
 throttle('sign:'+initial.id);if(!await verifyPassword(b.password,initial.password_hash))throw new HttpError(403,'Your current password is incorrect.');
 db.exec('BEGIN IMMEDIATE');try{
  const actor=requireRole(request,['super_admin','admin']);if(actor.password_hash!==initial.password_hash)throw new HttpError(409,'Your credentials changed. Sign in again.');
  const e=db.prepare('SELECT * FROM employees WHERE id=?').get(b.employeeId);if(!e||!['Offboarding','Offboarded'].includes(e.status))throw new HttpError(409,'Start offboarding before IT sign-off.');
  const pending=blockers(e.id,String(b.type));if(pending.length)throw new HttpError(409,pending.join(' '));
  if(db.prepare('SELECT id FROM departure_documents WHERE employee_id=? AND type=?').get(e.id,b.type))throw new HttpError(409,'This form is already signed. The saved record cannot be overwritten.');
  const id=randomUUID(),signed_at=new Date().toISOString(),snapshot=JSON.stringify(departureSnapshot(e.id)),note=b.note.trim();
  const digest=createHash('sha256').update(JSON.stringify({id,type:b.type,snapshot,signed_by:actor.id,signer_name:actor.name,signer_username:actor.username,signed_at,note})).digest('hex');
  db.prepare('INSERT INTO departure_documents(id,employee_id,type,snapshot,signed_by,signer_name,signer_username,signed_at,note,digest) VALUES(?,?,?,?,?,?,?,?,?,?)').run(id,e.id,b.type,snapshot,actor.id,actor.name,actor.username,signed_at,note,digest);
  audit(actor.id,'departure_signed:'+b.type,id);db.prepare('INSERT INTO events(id,employee_id,message,created_at) VALUES(?,?,?,?)').run(randomUUID(),e.id,`${b.type} signed by IT: ${actor.name}`,signed_at);db.exec('COMMIT');return Response.json({ok:true,id},{headers});
 }catch(e){db.exec('ROLLBACK');throw e}
}catch(e){return failure(e)}}
