import { sqliteTable, text, integer, blob, primaryKey, check, index, uniqueIndex } from 'drizzle-orm/sqlite-core';
export const employees = sqliteTable('employees', { id:text('id').primaryKey(), code:text('code').notNull().unique(), name:text('name').notNull(), email:text('email').notNull().unique(), department:text('department').notNull(), role:text('role').notNull(), startDate:text('start_date').notNull(), endDate:text('end_date'), status:text('status').notNull().default('Onboarding') });
export const assets = sqliteTable('assets', { id:text('id').primaryKey(), tag:text('tag').notNull().unique(), name:text('name').notNull(), kind:text('kind').notNull(), serial:text('serial').notNull().default(''), seats:integer('seats').notNull().default(1), state:text('state').notNull().default('Ready'), details:text('details').notNull().default('{}') });
export const assignments = sqliteTable('assignments', { id:text('id').primaryKey(), employeeId:text('employee_id').notNull().references(()=>employees.id), assetId:text('asset_id').notNull().references(()=>assets.id), identifier:text('identifier').notNull().default(''), assignedAt:text('assigned_at').notNull(), resolvedAt:text('resolved_at'), resolution:text('resolution') }, t=>[index('idx_assignments_employee').on(t.employeeId),index('idx_assignments_asset').on(t.assetId)]);
export const events = sqliteTable('events', { id:text('id').primaryKey(), employeeId:text('employee_id').references(()=>employees.id), message:text('message').notNull(), createdAt:text('created_at').notNull() });

export const maintenance = sqliteTable('maintenance', {id:text('id').primaryKey(),assetId:text('asset_id').notNull().references(()=>assets.id),type:text('type').notNull(),issue:text('issue').notNull(),provider:text('provider').notNull().default(''),openedDate:text('opened_date').notNull(),dueDate:text('due_date'),completedDate:text('completed_date'),workDone:text('work_done').notNull().default(''),cost:text('cost').notNull().default(''),currency:text('currency').notNull().default('PHP'),createdAt:text('created_at').notNull()},t=>[index('idx_maintenance_asset').on(t.assetId)]);
export const assetEvents=sqliteTable('asset_events',{id:text('id').primaryKey(),assetId:text('asset_id').notNull().references(()=>assets.id),message:text('message').notNull(),snapshot:text('snapshot').notNull().default(''),createdAt:text('created_at').notNull()},t=>[index('idx_asset_events_asset').on(t.assetId)]);
export const kitTemplates=sqliteTable('kit_templates',{id:text('id').primaryKey(),name:text('name').notNull(),items:text('items').notNull(),updatedAt:text('updated_at').notNull()});
export const employeeKits=sqliteTable('employee_kits',{id:text('id').primaryKey(),employeeId:text('employee_id').notNull().unique().references(()=>employees.id),name:text('name').notNull(),createdAt:text('created_at').notNull()});
export const kitTasks=sqliteTable('kit_tasks',{id:text('id').primaryKey(),kitId:text('kit_id').notNull().references(()=>employeeKits.id),employeeId:text('employee_id').notNull().references(()=>employees.id),label:text('label').notNull(),kind:text('kind').notNull(),quantity:integer('quantity').notNull().default(1),parentId:text('parent_id'),state:text('state').notNull().default('Pending'),assignmentId:text('assignment_id').unique().references(()=>assignments.id),accountRequestId:text('account_request_id').references(()=>accountRequests.id),note:text('note').notNull().default(''),completedAt:text('completed_at'),clearedAt:text('cleared_at')},t=>[index('idx_kit_tasks_employee').on(t.employeeId)]);
import { sql } from 'drizzle-orm';
export const accountRequests=sqliteTable('account_requests',{id:text('id').primaryKey(),employeeId:text('employee_id').notNull().references(()=>employees.id),provider:text('provider').notNull(),username:text('username').notNull(),services:text('services').notNull(),requester:text('requester').notNull(),source:text('source').notNull(),purpose:text('purpose').notNull(),reference:text('reference').notNull().default(''),status:text('status').notNull().default('Submitted'),reviewNote:text('review_note').notNull().default(''),createdAt:text('created_at').notNull(),updatedAt:text('updated_at').notNull()},t=>[index('idx_account_requests_employee').on(t.employeeId),uniqueIndex('idx_account_requests_open_username').on(t.provider,t.username).where(sql`status IN ('Submitted','Approved','Active')`)]);

export const employeeForms=sqliteTable('employee_forms',{id:text('id').primaryKey(),employeeId:text('employee_id').references(()=>employees.id),type:text('type').notNull(),status:text('status').notNull().default('Submitted'),payload:text('payload').notNull(),submittedBy:text('submitted_by').notNull(),submittedAt:text('submitted_at').notNull(),reviewedBy:text('reviewed_by'),reviewNote:text('review_note'),reviewedAt:text('reviewed_at')});
export const formApplications=sqliteTable('form_applications',{formId:text('form_id').primaryKey().notNull().references(()=>employeeForms.id)});
export const formAssetLinks=sqliteTable('form_asset_links',{id:text('id').primaryKey(),formId:text('form_id').notNull().references(()=>employeeForms.id),assetId:text('asset_id').notNull().references(()=>assets.id)},t=>[index('idx_form_asset').on(t.assetId)]);
export const formFiles=sqliteTable('form_files',{id:text('id').primaryKey(),formId:text('form_id').references(()=>employeeForms.id),name:text('name').notNull(),mime:text('mime').notNull(),size:integer('size').notNull(),createdAt:text('created_at').notNull()});

export const suppliers=sqliteTable('suppliers',{
 id:text('id').primaryKey(),name:text('name').notNull().unique(),category:text('category').notNull().default(''),contact:text('contact').notNull().default(''),email:text('email').notNull().default(''),phone:text('phone').notNull().default(''),address:text('address').notNull().default(''),notes:text('notes').notNull().default(''),source:text('source').notNull().default(''),active:integer('active').notNull().default(1),version:integer('version').notNull().default(1),createdAt:text('created_at').notNull(),updatedAt:text('updated_at').notNull()
},t=>[check('supplier_active',sql`${t.active} IN (0,1)`)]);
export const procurements=sqliteTable('procurements',{
 id:text('id').primaryKey(),supplierId:text('supplier_id').notNull().references(()=>suppliers.id),supplierName:text('supplier_name').notNull(),reference:text('reference').notNull(),purchaseDate:text('purchase_date').notNull(),description:text('description').notNull(),amountCents:integer('amount_cents').notNull(),currency:text('currency').notNull().default('PHP'),status:text('status').notNull().default('Recorded'),notes:text('notes').notNull().default(''),version:integer('version').notNull().default(1),createdAt:text('created_at').notNull(),updatedAt:text('updated_at').notNull()
},t=>[uniqueIndex('procurement_supplier_reference').on(t.supplierId,t.reference),check('procurement_amount',sql`${t.amountCents} >= 0`),check('procurement_status',sql`${t.status} IN ('Recorded','Voided')`)]);
export const procurementAssets=sqliteTable('procurement_assets',{procurementId:text('procurement_id').notNull().references(()=>procurements.id),assetId:text('asset_id').notNull().references(()=>assets.id)},t=>[primaryKey({columns:[t.procurementId,t.assetId]})]);
export const procurementInvoices=sqliteTable('procurement_invoices',{id:text('id').primaryKey(),procurementId:text('procurement_id').notNull().references(()=>procurements.id),name:text('name').notNull(),mime:text('mime').notNull(),size:integer('size').notNull(),content:blob('content',{mode:'buffer'}).notNull(),createdAt:text('created_at').notNull(),createdBy:text('created_by').notNull()},t=>[index('idx_invoice_procurement').on(t.procurementId)]);
export const employeeLaptopArrangements=sqliteTable('employee_laptop_arrangements',{employeeId:text('employee_id').primaryKey().references(()=>employees.id),personalUse:text('personal_use').notNull().default('Unknown'),personalDetails:text('personal_details').notNull().default(''),loanStatus:text('loan_status').notNull().default('Unknown'),loanReference:text('loan_reference').notNull().default(''),loanDate:text('loan_date').notNull().default(''),loanDetails:text('loan_details').notNull().default(''),notes:text('notes').notNull().default(''),version:integer('version').notNull().default(1),updatedAt:text('updated_at').notNull()},t=>[check('personal_use',sql`${t.personalUse} IN ('Unknown','Yes','No')`),check('loan_status',sql`${t.loanStatus} IN ('Unknown','None','Active','Completed','Cancelled')`)]);
export const purchasingHistory=sqliteTable('purchasing_history',{id:text('id').primaryKey(),entity:text('entity').notNull(),entityId:text('entity_id').notNull(),action:text('action').notNull(),actor:text('actor').notNull(),snapshot:text('snapshot').notNull(),createdAt:text('created_at').notNull()},t=>[index('idx_purchasing_history').on(t.entity,t.entityId,t.createdAt)]);
