import {activeBorrowingAssets} from '@/server/borrowing.mjs';
import {requireSignedClearance} from '@/server/departures.mjs';
import {currentUser} from '@/server/auth.mjs';
import {protect} from '@/server/guards';
import {formAction} from '@/lib/form-service';
import { accountAction } from '@/lib/account-service';
import { kitAction } from '@/lib/kit-service';
import { assetAction } from '@/lib/asset-service';
import { database } from '@/db';
const json=(data:unknown,status=200)=>Response.json(data,{status,headers:{'Cache-Control':'no-store'}});
async function originalGET(){try{const db=database();const [employees,assets,assignments,events,maintenance,assetEvents,templates,kits,tasks,accountRequests,forms,formFiles,formLinks]=await db.batch([db.prepare('SELECT * FROM employees ORDER BY name'),db.prepare('SELECT * FROM assets ORDER BY kind,name'),db.prepare('SELECT * FROM assignments ORDER BY assigned_at DESC'),db.prepare('SELECT * FROM events ORDER BY created_at DESC LIMIT 100'),db.prepare('SELECT * FROM maintenance ORDER BY opened_date DESC,created_at DESC'),db.prepare('SELECT * FROM asset_events ORDER BY created_at DESC'),db.prepare('SELECT * FROM kit_templates ORDER BY name'),db.prepare('SELECT * FROM employee_kits'),db.prepare('SELECT * FROM kit_tasks'),db.prepare('SELECT * FROM account_requests ORDER BY created_at DESC'),db.prepare('SELECT * FROM employee_forms ORDER BY submitted_at DESC'),db.prepare('SELECT * FROM form_files WHERE form_id IS NOT NULL'),db.prepare('SELECT * FROM form_asset_links')]);const loanAssets=new Map(activeBorrowingAssets().map((b:any)=>[b.asset_id,b]));return json({employees:employees.results,assets:assets.results.map((a:any)=>({...a,borrow_status:(loanAssets.get(a.id) as any)?.status,borrow_employee_id:(loanAssets.get(a.id) as any)?.employee_id})),assignments:assignments.results,events:events.results,maintenance:maintenance.results,assetEvents:assetEvents.results,templates:templates.results,kits:kits.results,tasks:tasks.results,accountRequests:accountRequests.results,forms:forms.results,formFiles:formFiles.results,formLinks:formLinks.results});}catch{return json({error:'Unable to load workspace. Please try again.'},500);}}
function value(body:any,key:string,max=200){const v=body[key];if(typeof v!=='string'||!v.trim()||v.length>max)throw new Error(`Please enter a valid ${key}.`);return v.trim();}
function date(body:any,key:string){const s=value(body,key,10);if(!/^\d{4}-\d{2}-\d{2}$/.test(s)||!Number.isFinite(Date.parse(s))||new Date(s).toISOString().slice(0,10)!==s)throw new Error('Please enter a valid date.');return s;}
async function originalPOST(request:Request){if(request.headers.get('sec-fetch-site')==='cross-site')return json({error:'Cross-site request denied.'},403);try{const body:any=await request.json();const db=database(),id=crypto.randomUUID(),now=new Date().toISOString();let employeeId:string|null=null,message='';
if(['submitForm','approveForm','rejectForm'].includes(body.action)){if(body.action!=='submitForm')body.reviewer=currentUser(request).name;const result=await formAction(db,body,id,now);return json({ok:true,id,message:result.message});}
if(body.action==='employee'){const name=value(body,'name'),email=value(body,'email').toLowerCase();if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email))throw new Error('Please enter a valid email.');await db.prepare('INSERT INTO employees (id,code,name,email,department,role,start_date,status) VALUES (?,?,?,?,?,?,?,?)').bind(id,value(body,'code'),name,email,value(body,'department'),value(body,'role'),date(body,'startDate'),'Onboarding').run();employeeId=id;message=`${name} added for onboarding`;}
else if(['accountRequest','accountApprove','accountReject','accountCancel','accountRecordCreated','accountDisable'].includes(body.action)){message=await accountAction(db,body,id,now);employeeId=body.employeeId;}
else if(['saveTemplate','applyKit','fulfillKitTask','skipKitTask','clearKitTask'].includes(body.action)){message=await kitAction(db,body,id,now);employeeId=body.employeeId||null;}
else if(['asset','editAsset','maintenance','completeMaintenance'].includes(body.action)){message=await assetAction(db,body,id,now);}
else {employeeId=value(body,'employeeId');const employee:any=await db.prepare('SELECT * FROM employees WHERE id=?').bind(employeeId).first();if(!employee)throw new Error('Employee not found.');
if(body.action==='assign'){const assetId=value(body,'assetId');const asset:any=await db.prepare('SELECT * FROM assets WHERE id=?').bind(assetId).first();if(!asset)throw new Error('Asset not found.');if(asset.kind==='Account')throw Error('Create accounts through Account requests, not inventory.');const identifier=asset.kind==='Account'?value(body,'identifier'):String(body.identifier||'').slice(0,200);const result=await db.prepare(`INSERT INTO assignments (id,employee_id,asset_id,identifier,assigned_at) SELECT ?,?,?,?,? WHERE EXISTS(SELECT 1 FROM employees WHERE id=? AND status IN ('Onboarding','Active')) AND NOT EXISTS(SELECT 1 FROM account_requests WHERE employee_id=? AND status IN ('Submitted','Approved')) AND (SELECT COUNT(*) FROM assignments WHERE asset_id=? AND resolved_at IS NULL)<(SELECT seats FROM assets WHERE id=? AND state='Ready') AND NOT EXISTS(SELECT 1 FROM assignments WHERE employee_id=? AND asset_id=? AND resolved_at IS NULL)`).bind(id,employeeId,assetId,identifier,now,employeeId,employeeId,assetId,assetId,employeeId,assetId).run();if(!result.meta.changes)throw new Error('This asset is unavailable, already assigned, or the employee is leaving.');message=`${asset.name} provisioned to ${employee.name}`;}
else if(body.action==='resolve'){const assignmentId=value(body,'assignmentId');const a:any=await db.prepare('SELECT a.*,s.name,s.kind FROM assignments a JOIN assets s ON s.id=a.asset_id WHERE a.id=? AND a.employee_id=?').bind(assignmentId,employeeId).first();if(!a)throw new Error('Assignment not found.');const resolution=a.kind==='Hardware'?'Returned':a.kind==='Software'?'License revoked':'Account deactivated';const result=await db.prepare('UPDATE assignments SET resolved_at=?,resolution=? WHERE id=? AND employee_id=? AND resolved_at IS NULL').bind(now,resolution,assignmentId,employeeId).run();if(!result.meta.changes)throw new Error('This item has already been resolved.');message=`${a.name}: ${resolution.toLowerCase()} for ${employee.name}`;}
else if(body.action==='activate'){const result=await db.prepare(`UPDATE employees SET status='Active' WHERE id=? AND status='Onboarding' AND EXISTS(SELECT 1 FROM assignments WHERE employee_id=? AND resolved_at IS NULL) AND NOT EXISTS(SELECT 1 FROM kit_tasks WHERE employee_id=employees.id AND state='Pending') AND NOT EXISTS(SELECT 1 FROM account_requests WHERE employee_id=employees.id AND status IN ('Submitted','Approved'))`).bind(employeeId,employeeId).run();if(!result.meta.changes)throw new Error('Provision at least one asset and finish all kit tasks before completing onboarding.');message=`${employee.name} completed onboarding`;}
else if(body.action==='offboard'){const end=date(body,'endDate'),reason=value(body,'departureReason');if(!['Resignation','End of contract','Retirement','Other'].includes(reason))throw new Error('Choose a departure reason.');if(end<employee.start_date)throw new Error('Last working day cannot precede the start date.');const result=await db.prepare(`UPDATE employees SET status='Offboarding',end_date=?,departure_reason=? WHERE id=? AND status IN ('Active','Onboarding')`).bind(end,reason,employeeId).run();if(!result.meta.changes)throw new Error('Employee is already offboarding or offboarded.');message=`Offboarding started for ${employee.name}`;}
else if(body.action==='complete'){requireSignedClearance(employeeId);const result=await db.prepare(`UPDATE employees SET status='Offboarded' WHERE id=? AND status='Offboarding' AND (SELECT COUNT(*) FROM departure_documents WHERE employee_id=employees.id)=2 AND NOT EXISTS(SELECT 1 FROM app_users WHERE employee_id=employees.id AND active=1) AND NOT EXISTS(SELECT 1 FROM assignments WHERE employee_id=? AND resolved_at IS NULL) AND NOT EXISTS(SELECT 1 FROM kit_tasks WHERE employee_id=employees.id AND state='Provisioned' AND assignment_id IS NULL AND account_request_id IS NULL) AND NOT EXISTS(SELECT 1 FROM account_requests WHERE employee_id=employees.id AND status IN ('Submitted','Approved','Active'))`).bind(employeeId,employeeId).run();if(!result.meta.changes)throw new Error('Resolve all assigned assets, accessories, and service access before completing offboarding.');message=`${employee.name} completed offboarding`;}
else throw new Error('Unknown action.');}
await db.prepare('INSERT INTO events (id,employee_id,message,created_at) VALUES (?,?,?,?)').bind(crypto.randomUUID(),employeeId,message,now).run();return json({ok:true,id,message});
}catch(error){const message=error instanceof Error?error.message:'';if(/UNIQUE constraint/i.test(message))return json({error:'That record already exists, a kit is already applied, or an assignment is already linked.'},409);if(/D1_|SQLITE|database/i.test(message))return json({error:'Unable to save. Refresh the workspace and try again.'},500);return json({error:message||'Unable to save. Please try again.'},400);}}
export const GET=protect(originalGET);
export const POST=protect(originalPOST);
